### ISSUE TITLE
JVM crash SIGSEGV libgtk-3.so.0+0x2bad99

### ISSUE THREAD

**Issue by theangrydev** [dorkbox/SystemTray#100]
On Ubuntu 16.0.4 I get the following crash:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa99f98bd99, pid=24803, tid=0x00007fab000c4700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgtk-3.so.0+0x2bad99]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007faaf8011800):  JavaThread "main" [_thread_in_native, id=24805, stack(0x00007faafffc4000,0x00007fab000c5000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

...

Stack: [0x00007faafffc4000,0x00007fab000c5000],  sp=0x00007fab000c0860,  free space=1010k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libgtk-3.so.0+0x2bad99]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  dorkbox.util.jna.linux.Gtk3.gtk_offscreen_window_new()Lcom/sun/jna/Pointer;+0
j  dorkbox.util.jna.linux.GtkTheme$1.run()V+3
j  dorkbox.util.jna.linux.GtkEventDispatch$4.run()V+4
j  dorkbox.util.jna.linux.GtkEventDispatch$5.callback(Lcom/sun/jna/Pointer;)I+14
v  ~StubRoutines::call_stub
j  dorkbox.util.jna.linux.Gtk3.g_main_context_invoke(Ldorkbox/util/jna/linux/GMainContext;Ldorkbox/util/jna/linux/FuncCallback;Lcom/sun/jna/Pointer;)V+0
j  dorkbox.util.jna.linux.GtkEventDispatch.dispatch(Ljava/lang/Runnable;)V+114
j  dorkbox.util.jna.linux.GtkEventDispatch.dispatchAndWait(Ljava/lang/Runnable;)V+42
j  dorkbox.util.jna.linux.GtkTheme.getMenuEntryImageSize()I+16
j  dorkbox.systemTray.util.SizeAndScalingUtil.getMenuImageSize(Ljava/lang/Class;)I+103
j  dorkbox.systemTray.SystemTray.init()V+1631
j  dorkbox.systemTray.SystemTray.get()Ldorkbox/systemTray/SystemTray;+0
j  <snip>
v  ~StubRoutines::call_stub

```

**Comment by dorkbox** [comment]
I am waiting on a response to this issue: https://github.com/java-native-access/jna/issues/1099

**Comment by Steve0212a** [comment]
I am getting this on Ubuntu 18.04 too.  Any ETA on this?

**Comment by dorkbox** [comment]
Sadly, they didn't accept the changes, so I'm going to have to make some more serious changes to the library for cross platform support :( I'm leaving this issue open so I can track what's going on.

**Comment by Steve0212a** [comment]
thx for the update

**Comment by ouranostech** [comment]
I am getting crash with this warning on ubuntu 18.04, I am using JavaFX 8

`ERROR 13722 --- [lication Thread] dorkbox.systemTray.SystemTray            : GNOME shell detected, but UNKNOWN type. This should never happen. Falling back to GtkStatusIcon. Please create an issue with as many details as possible.`

Here is part error dump 

`# A fatal error has been detected by the Java Runtime Environment:
#  SIGSEGV (0xb) at pc=0x00007fe76c92385c, pid=11111, tid=0x00007fe76c8d4700
# JRE version: Java(TM) SE Runtime Environment (8.0_241-b07) (build 1.8.0_241-b07)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.241-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgdk-x11-2.0.so.0+0x4e85c]  gdk_display_open+0x5c

---------------  T H R E A D  ---------------

Current thread (0x00007fe75c2b6800):  JavaThread "GTK Native Event Loop" [_thread_in_native, id=11160, stack(0x00007fe76c7d4000,0x00007fe76c8d5000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000114

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x00007fe73c00a570 is an unknown value
RCX=0x0000000000000000 is an unknown value
RDX=0x0000000000000000 is an unknown value
RSP=0x00007fe76c8d2c60 is pointing into the stack for thread: 0x00007fe75c2b6800
RBP=0x00007fe76c8d2c70 is pointing into the stack for thread: 0x00007fe75c2b6800
RSI=0x00007fe76c923650: <offset 0x4e650> in /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 at 0x00007fe76c8d5000
RDI=0x00007fe73c00a570 is an unknown value
R8 ={method} {0x00007fe76d748420} 'callback' '(Ljava/lang/String;ILjava/lang/String;Lcom/sun/jna/Pointer;)V' in 'dorkbox/util/jna/linux/Glib$1'
R9 =0x0000000000000006 is an unknown value
R10=0x00007fe76d1f8734: ffi_closure_unix64+0x9e in /tmp/jna-375904307/jna7630813227684495146.tmp at 0x00007fe76d1e5000
R11=0x00007fe76d1f86f8: ffi_closure_unix64+0x62 in /tmp/jna-375904307/jna7630813227684495146.tmp at 0x00007fe76d1e5000
R12=0x00007fe76c8d2ca0 is pointing into the stack for thread: 0x00007fe75c2b6800
R13=0x0000000000000004 is an unknown value
R14=0x0000000000000001 is an unknown value
R15=0x00007fe76c8d37d0 is pointing into the stack for thread: 0x00007fe75c2b6800


Stack: [0x00007fe76c7d4000,0x00007fe76c8d5000], sp=0x00007fe76c8d2c60, free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C [libgdk-x11-2.0.so.0+0x4e85c] gdk_display_open+0x5c
C 0x0000000000000000

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j dorkbox.util.jna.linux.Gtk2.gtk_init_check(I)Z+0
j dorkbox.util.jna.linux.GtkEventDispatch$2.run()V+36
v ~StubRoutines::call_stub
`

**Comment by dorkbox** [comment]
Because of internal changes to Java and JavaFX, I have to change how this library interacts with JavaFX and SWT.

**Comment by ouranostech** [comment]
Thank you for quick reply.

**Comment by St3pp3nw0lf82** [comment]
Hi, I'm not sure if this is already fixed but I'm facing the same problem. I'm running my application on IgelOS, which is based on Linux Ubuntu. Here are some details about the OS itself and the underlying Java environment on my device:

**Linux System**:
Linux 5.4.48 #mainline-lxos-g1605521351 SMP PREEMPT 2020-11-16 10:49 UTC x86_64 x86_64 x86_64 GNU/Linux

**Java environment**:
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.runtime.version = 1.8.0_262-b19
java.specification.version = 1.8
java.vendor = Azul Systems, Inc.
java.vendor.url = http://www.azulsystems.com/
OpenJDK Runtime Environment (Zulu 8.48.0.51-CA-linux64) (build 1.8.0_262-b19)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.51-CA-linux64) (build 25.262-b19, mixed mode)

In the beginning, the Systemtray library wasn't able to autodetect the correct desktop environment which resulted finally in using Swing as Traytype. It worked as long as my application was started as root user, but the trayicon did not appear when I launched the application with regular user rights. I got in contact with Igel themselves and asked them what desktop environment their OS is using and they said it is XFCE.
So I forced the Systemtray library to "manually" always use XFCE as desktop environment and the initial result was very good, the rendered trayicon looked much better then the previous one and - the best thing about it - it also worked with regular user rights.
But as soon as I click on the trayicon, the following fatal error appears:

![java-fatal-error](https://user-images.githubusercontent.com/1822500/108168777-23d08300-70f8-11eb-8820-d2381c8710ca.png)

The fact the trayicon looks so good and it also works with user rights, I really would like to continue on this path. Running the application always as root user is not an option.

Are there already any updates on this? I also keep on looking for a solution.

**Comment by dorkbox** [comment]
Can you enable debug, and send me the output?

**Comment by St3pp3nw0lf82** [comment]
Hi,
thank you for your quick reply! Below is the debug log output:

12:59:20.017 [Thread: main] ERROR dorkbox.systemTray.SystemTray - is linux: true
12:59:20.018 [Thread: main] ERROR dorkbox.systemTray.SystemTray - is windows: false
12:59:20.018 [Thread: main] ERROR dorkbox.systemTray.SystemTray - is mac: false
12:59:20.176 [Thread: main] ERROR dorkbox.systemTray.SystemTray - isNix...
12:59:20.176 [Thread: main] ERROR dorkbox.systemTray.SystemTray - loaded GTK version: 0
12:59:20.176 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - javaFX is loaded?: false
12:59:20.180 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - OS: Linux
12:59:20.180 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Arch: amd64
12:59:20.181 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Oracle Corporation OpenJDK 64-Bit Server VM 1.8.0_262
12:59:20.181 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Is Auto sizing tray/menu? true
12:59:20.181 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Is JavaFX detected? false
12:59:20.181 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Is SWT detected? false
12:59:20.236 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Java Swing L&F: Metal
12:59:20.237 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
12:59:20.237 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Force GTK2: false
12:59:20.237 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Prefer GTK3: true
12:59:20.268 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'Unknown' desktop environment
DISTRIB_ID=IGEL
DISTRIB_RELEASE=V11
DISTRIB_CODENAME="IGEL OS 11"
DISTRIB_DESCRIPTION="IGEL OS 11 (64bit)"
HELP_URLS=""
NAME="IGEL OS 11"
VERSION="11.04.240"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="IGEL OS 11.04.240"
VERSION_ID="18.04"
HOME_URL="http://www.igel.com/"
SUPPORT_URL="https://support.igel.com"
BUG_REPORT_URL="https://www.igel.com/submit-a-ticket/"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
IGEL OS 11.04.240

12:59:20.270 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - desktop environment is XFCE on Igel
12:59:20.271 [Thread: main] DEBUG dorkbox.systemTray.SystemTray - selected traytype: class dorkbox.systemTray.ui.gtk._GtkStatusIconNativeTray

If you need any further information about the underlying system, please let me know, I will pass your questions on to the development team of the IgelOS.

**Comment by dorkbox** [comment]
Perfect.

I'll add this info (and do a basic check on IGEL) and push updates to the 
libraries.

To double check, the DE is based on XFCE?

**Comment by St3pp3nw0lf82** [comment]
Hi, yes, desktop environment on Igel is XFCE

**Comment by St3pp3nw0lf82** [comment]
Hi,
   
  
  
   if you get your library running on IgelOS and if there is an updated version of the library available, please let me know.
   
  
  
   
  
  
   Thanks in advance
   
  
  
   
    dorkbox <notifications@github.com> hat am 18.02.2021 13:47 geschrieben:
   
   
    
   
   
    
   
   Perfect.
   
   I'll add this info (and do a basic check on IGEL) and push updates to the 
   libraries.
   
   To double check, the DE is based on XFCE?

**Comment by dorkbox** [comment]
This is now working in IgelOS 11 as a normal user. Thank you again for the bug report! This will be part of the 4.0 release.

![image](https://user-images.githubusercontent.com/5301521/111886680-d766b480-89cf-11eb-9eae-0e247ecac242.png)
