### ISSUE TITLE
MenuItem don't remove before peer binding

### ISSUE THREAD

**Issue by polyn0m** [dorkbox/SystemTray#102]
**OS:** MacOS
**MenuType:** AwtMenu

Description:
I'm create tray icon and menu. Then i try remove menu entry (very fast) and it don't removed from menu. I debug this issue and see this:
```
public
void remove() {
if (peer != null) {
        peer.remove();

        this.parent = null;
        this.systemTray = null;
        peer = null;
   }
}
```
`peer` is null, because binding is not execute in `AwtMenu` class in method `add`
```
// must always be called on the EDT
SwingUtil.invokeLater(new Runnable() {
...
}
```
If wait some time runnable called and all works fine, but i think it's not normal behavior.

**Comment by dorkbox** [comment]
Fixed in baec7098ea29aaad9fd05e2d37aca708478aff27
