### ISSUE TITLE
Popup position wrong when using scaling other than 100% on Windows

### ISSUE THREAD

**Issue by cmf-cv** [dorkbox/SystemTray#104]
SystemTray is a great lib, thanks a lot for creating and maintaining it!

When using scaling settings other than 100% on Windows 10 with JDK11 (and others) and SystemTray version 3.17, the popup menu shows up at the lower right corner of the screen instead of the clicked position.

The reason seems to be that in _WindowsNativeTray.class in line 199 the click position is retrieved by User32.User32.GetCursorPos(mousePosition) which returns "raw" coordinates which do not regard scaling settings. Then popupMenu.doShow(point, 0) is called with those coordinates. (When calling popupMenu.doShow(point, 0) with "scaled" coordinates it works fine.)

I tested this with JDKs 10 to 12 (OpenJDK and OracleJDK), different scaling settings (100-200%), different monitors and I'm using SystemTray in a JavaFX (gradle) application with OpenJFX. Also tested it on another computer, same there.

With JDK 1.8 the popup shows up correctly at the clicked position but it's not scaled correctly and appears too small.

**Comment by dorkbox** [comment]
Oh interesting find. I'll add scaling checks. Thanks for the report!

**Comment by PatrickJSweeney** [comment]
Has this issue been addressed?  I'm seeing similar behavior with the swing implementation on windows 10 with version 3.17

**Comment by dorkbox** [comment]
I haven't gotten to this yet - i just finished getting some library updates/changes in.  Thanks for the reminder!

**Comment by dorkbox** [comment]
Fixed this, thanks!
