### ISSUE TITLE
Can´t find dependent libraries in Windows 7

### ISSUE THREAD

**Issue by mataide** [dorkbox/SystemTray#106]
I got an user reporting this error on a Windows 7 Machine:
https://cdn.discordapp.com/attachments/545264496923508751/563424612004659220/unknown.png

The error occours in the line:
`this.systemTray = SystemTray.get();`

I do have a Windows 7 and couldnt re-create the issue. 
I couldnt find how this dll is created and why it is missing.

**Comment by mataide** [comment]
This is caused by using jna 4.2.2 being dynamically linked against msvcrt100.dll. This was reported and fixed for jna. It should be fixed for 4.3.0 I assume (most recent is 4.5.1; see java-native-access/jna#636).

This does not become obvious with using java 1.8 as the dll is part of the 1.8 jre's.

Please upgrade your dependency to jna to a newer persion ... ?

**Comment by dorkbox** [comment]
Thanks for the info - I will be updating the library -- there are a number of bugs as well that need to be fixed, I just haven't had time yet to do it.

**Comment by dorkbox** [comment]
JNA has been updated. The next release will have this fixed.
