### ISSUE TITLE
I am not getting any property to show menu as under the icon as system menu in ubuntu

### ISSUE THREAD

**Issue by DharmitSoni** [dorkbox/SystemTray#109]
I want the exectly the same as image, I want actually a menu under the icon as system dropdown in ubuntu please help me for that as soon as possible. I tried but not getting proper result from your library.

![dharmitsonierror](https://user-images.githubusercontent.com/52246747/60183589-366fb780-9844-11e9-82da-a7fc0b0009fd.png)

**Comment by DharmitSoni** [comment]
Please help me I need to complete this by today. I am waiting.

**Comment by dorkbox** [comment]
This is in the examples.
