### ISSUE TITLE
Add support for radio buttons

### ISSUE THREAD

**Issue by Sebastian-0** [dorkbox/SystemTray#111]
It would be nice to have support for radio buttons in the tray icon menus, currently that is the main thing that is holding me back from using this project.

**Comment by dorkbox** [comment]
It's not supported by app-indicator, sadly. Only checkbox and images. This library is a subset of what is supported across all tested operating systems.

Some OS features not normally supported I have implemented, but I'm not going to spend a huge amount of time getting a cross platform feature working when you can implement your own radio buttons using callbacks, setting the image, and enable/disable menu entries.

If you end up doing this, I welcome pull requests.
