### ISSUE TITLE
IllegalAccessError for SystemTray.get()

### ISSUE THREAD

**Issue by DesertCookie** [dorkbox/SystemTray#114]
I went off the example in [TestTrayJavaFX.java](https://github.com/dorkbox/SystemTray/blob/master/test/dorkbox/TestTrayJavaFX.java) and basically copied the code described there. When running I get the following error(s):
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: superclass access check failed: class dorkbox.systemTray.util.WindowsSwingUI$2 (in module SystemTray) cannot access class com.sun.java.swing.plaf.windows.WindowsMenuUI (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to module SystemTray
```
The stack trace points towards `SystemTray.get()` as the origin within my application.

I am using Java 11.0.6, SystemTray 3.17, and (obviously) make use of project Jigsaw in my project.

**Comment by oxodao** [comment]
Same reason as [this](https://github.com/dorkbox/SystemTray/issues/119#issuecomment-686468133)

**Comment by dorkbox** [comment]
It sadly doesn't work with JPMS yet. I'm working on a solution though

**Comment by dorkbox** [comment]
Of note, this solution will remove class re-writing - so it will be java 9+ only.

**Comment by dorkbox** [comment]
This has been fixed. Class re-writing (to fix certain problems on older JVMs) no longer happens with java9+
