### ISSUE TITLE
Linux Mint 19.3 not showing image

### ISSUE THREAD

**Issue by RocketJannis** [dorkbox/SystemTray#116]
the image is not showing up on Linux Mint 19.3 with the new XApp-Status-Applet

**Comment by zendawg** [comment]
@RocketJannis  see issue #125 - we were having a similar issue using Pop!_OS. Take a look at comments toward the end - you need to convince SystemTray that your `GDMSESSION` is `ubuntu`. Take a look at the output from a CLI shell of the value of

```
echo $GDMSESSION
```

If the result is not `ubuntu`, take a look at the solution toward the end of the issue given above to see how to fix this.

Be sure to take a look at the section in the same issue to enable verbose debugging if you think that will help you.

I expect this to impact all Ubuntu-derived systems that change their `ID` in the `/etc/os-release` file.

**Comment by dorkbox** [comment]
This is fixed and tested on LinuxMint 19.03 (and also 20).

Thanks for the bug report!
