### ISSUE TITLE
Detect when system tray main menu is opened

### ISSUE THREAD

**Issue by bozjator** [dorkbox/SystemTray#117]
Hi,

is there a way to detect when user clicks on a system tray icon?
I would like to call api and update status when system tray main menu is opened, but i can not find a way to detect this.
Do you have any suggestions how to achieve this?

Regards

**Comment by dorkbox** [comment]
Sadly, there is no cross platform way to do this, so it is not supported.

If you have just a windows install, you can create your own system tray and detect when the icon is clicked on.
