### ISSUE TITLE
SystemTray doesn't show sometimes in Ubuntu 19.04

### ISSUE THREAD

**Issue by s-glatshtein** [dorkbox/SystemTray#118]
Hello,
I've encountered this a few times, but it is very inconsistent. Sometimes when i create my system tray icon on ubuntu i get this error in the log:
`d.u.j.l.GtkTheme                         Unable to get tray menu image size. Using default.`
I have no idea what is causing this. Do you have any idea? This is the only log that changes between working and not-working states

**Comment by dorkbox** [comment]
This is fixed now, and should not be happening any more.
