### ISSUE TITLE
dorkbox.util package missing when building the jar locally

### ISSUE THREAD

**Issue by RaviOnline** [dorkbox/SystemTray#120]
I tried building the 3.17 jar locally using the `publishToMavenLocal` Gradle task but it doesn't include the `dorkbox.util` package in the generated jar.

Instead, it lists an independent dependency on `com.dorkbox:Utilities:1.1` which has a lot more classes and pulls in several other unrelated dependencies (like, bouncycastle cryptography) as well.

I tried deleting the files manually from the `Utilities.jar` but some of the classes are not even present or present in different packages (like, the `dorkbox.util.JavaFX` class).

So, how to go about building the same 3.17 jar that's currently available in maven central but locally instead?

**Comment by zendawg** [comment]
Also interested to find out how to compile this project - I've commented in #125.

If you find out how to compile with success, please be sure to reproduce your steps here as I'd like to create some pull requests for this project.

By the way, I do not see the `publishToMavenLocal` listed in the tasks. All help appreciated.

**Comment by dorkbox** [comment]
I will make some changes to the build so it works better. There are 
complications because of how JNA and SWT are used, and because gradle is a 
little bit of a PITA to get it to do exactly what you want.

I'm almost done with another project, and can focus more time on this when 
finished.

**Comment by zendawg** [comment]
Brilliant, thanks for your feedback and great project.

If you check out #125 (near the end), I think I've found the reason why some recent Ubuntu flavours (Mint, Pop etc.) are not working - although it's a shell-based hack, I can see how and where it relates directly to the code (hence the need for me to build so I could raise a pull request).

**Comment by dorkbox** [comment]
I have updated the build.gradle.kts file, so it should now be correctly building again!
