### ISSUE TITLE
How to configure project and run Test File

### ISSUE THREAD

**Issue by mohds164** [dorkbox/SystemTray#128]
I open project in eclipse AND added jar file

https://git.dorkbox.com/dorkbox/SystemTray/releases
https://repo1.maven.org/maven2/com/dorkbox/ShellExecutor/
https://repo1.maven.org/maven2/net/java/dev/jna/jna/
https://repo1.maven.org/maven2/net/java/dev/jna/jna-platform/
https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
https://repo1.maven.org/maven2/org/javassist/javassist/

but still have more error.

import dorkbox.jna.linux.AppIndicator;
import dorkbox.jna.linux.Gtk;
import dorkbox.jna.linux.GtkCheck;
import dorkbox.jna.linux.GtkEventDispatch;
import dorkbox.util.javaFx.JavaFX;
import dorkbox.util.swt.Swt;

import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Text;

**Comment by dorkbox** [comment]
It's configured to use JetBrains IntelliJ and gradle. I don't use Eclipse anymore, so I can't help you with it.

Ideally, you would open the `build.gradle.kts` as a project, and let the IDE import everything.
