### ISSUE TITLE
Separate left/right click actions

### ISSUE THREAD

**Issue by Sebastian-0** [dorkbox/SystemTray#129]
Are there any plans for separating left/right click actions on the tray? In Swing, for instance, you can set a left click action on the tray: `trayIcon.addActionListener(...)` while the right click action was reserved for the popup-menu. Many programs use this mechanic for opening the main window on left click, which is something I would like to do as well. From what I know this is supported in many OSes/DEs so it would make sense if there is some kind of API available that you can use.

There was an old issue on the same subject (#78) that was closed a long time ago with no update since; do you have any new plans to share?

**Comment by dorkbox** [comment]
Even though some OS/DE combinations support it, not all do and sadly this functionality is not possible. This library only satisfies functionality that is the lowest common denominator and removes all the extra checks necessary by the developer for what OS/DE is currently running to have a working tray icon+menu.
