### ISSUE TITLE
Menu.add(Jmenu menu) throws NullPointerException when no image is set

### ISSUE THREAD

**Issue by ryantaplin** [dorkbox/SystemTray#130]
Menu.add(Jmenu entry) throws a NullPointerException if an image has not been set on it. 

I feel like image should be optional here.

**Comment by dorkbox** [comment]
What do the test examples show?

Also, can you give me a stack trace?

**Comment by ryantaplin** [comment]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at dorkbox.systemTray.Menu.add(Menu.java:151)
	at tray.ApplicationTray.setupSystemTray(ApplicationTray.java:83)
	at tray.ApplicationTray.<init>(ApplicationTray.java:48)
```

It assumes your JMenu entry has an icon and blows up when trying to `getIconWidth()` on the null icon. The line of code in question is here.  
```
Menu add(final JMenu entry) {
...
        Icon icon = entry.getIcon();
        BufferedImage bimage = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
        menu.setImage(bimage);
...
}
```

**Comment by dorkbox** [comment]
Ah hah! Found the error (someone else had reported this, but didn't give me a stack trace). It was also an issue in another place. Thanks for the report!
