### ISSUE TITLE
Scope for adding 'JText Field' into TaskTray

### ISSUE THREAD

**Issue by ryantaplin** [dorkbox/SystemTray#131]
Is it possible to add scope for 'JTextField' into the list of entries? I'm just throwing this out there incase this has already been looked into/answered previously.

I want to be able to add a 'filter field' to a Menu and filter out any of the menu entries text value's that don't meet the value.

This may be more appropriate for a separate ticket but whilst i'm on topic about menu items, i'd also like to look into having a 'sort' function on menu's to sort the text value's without having to manually tear down the whole list and rebuild it each time I get a new value. 

I've not played around awt,gtk,osx or swing before so it would take me some time to look into and implement but I'm more than happy to take a stab at it and create a merge request if I get anywhere with it.

**Comment by dorkbox** [comment]
Sadly, this won't work in Linux since only text labels (and in some cases, icons) are supported.

You could definitely have "sort" functionalitly, but it would have to be a label (a label with no text will have problems, as, some versions of linux don't support icons.

**Comment by ryantaplin** [comment]
Sorry for the delay in replying and thanks for the update.

Ok that's a little disappointing. I guess I can create a standalone menu button that brings up the standalone window that I can have some of this functionality in. In light of this news, i will close this ticket :+1:
