### ISSUE TITLE
Display of Trayicon requires root privileges

### ISSUE THREAD

**Issue by St3pp3nw0lf82** [dorkbox/SystemTray#134]
Hi, I'm currently developing a Java application for an operating system called IgelOS. It is developed by Igel Technology GmbH (https://www.igel.com) and is based on Linux.

When the application is started with root privileges, the trayicon shows up fine. But when launched as a regular user, the trayicon doesn't show up anymore although the application is running.
But unfortunately, running the application with root privileges is not an option.

When I activate Debug mode within the SystemTray library, it does not show any additional error hints. But the line of code that fails is right at the beginning with:

`SystemTray.get();`
The above line returns null.
My company has a partnership with Igel, so if there is anything they can change/modify or maybe add a required package to make this great library also work under user rights, please let me know.

Following are some information about the underlying Linux system and the installed Java environment:

**Linux System**:
Linux 5.4.48 #mainline-lxos-g1605521351 SMP PREEMPT 2020-11-16 10:49 UTC x86_64 x86_64 x86_64 GNU/Linux

**Java environment**:
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.runtime.version = 1.8.0_262-b19
java.specification.version = 1.8
java.vendor = Azul Systems, Inc.
java.vendor.url = http://www.azulsystems.com/
OpenJDK Runtime Environment (Zulu 8.48.0.51-CA-linux64) (build 1.8.0_262-b19)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.51-CA-linux64) (build 25.262-b19, mixed mode)

Do you have any ideas what might be the issue here?

**Comment by dorkbox** [comment]
This has been fixed for igel os 11. Thanks for the bug report and info!

See: https://github.com/dorkbox/SystemTray/issues/100#issuecomment-803469436

**Comment by St3pp3nw0lf82** [comment]
Hi,

 

Thank you so much, this one really gave me a hard time! So that’s really good news. Glad you got it working!

 

I’m using Maven in my project, so will there also be a 4.0 release on the Maven repository?

 

 

Thanks again and many greetings,

Johannes Cox

Software Developer


  <https://gisbo.de/gisbo_logo_72.jpg> 

	Gisbo Softwareentwicklung
und EDV-Beratung GmbH 
Etzelweg 234
D - 66482 Zweibrücken

	

 


E-Mail: ***@***.***
Web: www.gisbo.de <https://www.gisbo.de/> 

	Tel.: +49 (0) 6332 - 99 790 84
Fax: +49 (0) 6332 - 99 790 80

  _____  



Geschäftsführung: Sabine Eßer und Stella Bayer
Amtsgericht Zweibrücken HRB 1552Z, Steuernummer: 35/657/0427/7

 


 <https://www.youtube.com/watch?v=76OeqWr9kUY&feature=youtu.be>    <https://www.facebook.com/gisbo>   <https://www.instagram.com/gisboalarm/>    <https://twitter.com/GisboGmbh> 

 

 

Von: dorkbox ***@***.***> 
Gesendet: Montag, 22. März 2021 01:06
An: dorkbox/SystemTray ***@***.***>
Cc: St3pp3nw0lf82 ***@***.***>; Author ***@***.***>
Betreff: Re: [dorkbox/SystemTray] Display of Trayicon requires root privileges (#134)

 

This has been fixed for igel os 11. Thanks for the bug report and info!

See: #100 (comment) <https://github.com/dorkbox/SystemTray/issues/100#issuecomment-803469436>

**Comment by dorkbox** [comment]
Yes, 4.0 will release to maven.

**Comment by St3pp3nw0lf82** [comment]
That’s great! You know already roughly when it will be available on Maven?

 

Kind Regards,

Johannes Cox

Software Developer


  <https://gisbo.de/gisbo_logo_72.jpg> 

	Gisbo Softwareentwicklung
und EDV-Beratung GmbH 
Etzelweg 234
D - 66482 Zweibrücken

	

 


E-Mail: ***@***.***
Web: www.gisbo.de <https://www.gisbo.de/> 

	Tel.: +49 (0) 6332 - 99 790 84
Fax: +49 (0) 6332 - 99 790 80

  _____  



Geschäftsführung: Sabine Eßer und Stella Bayer
Amtsgericht Zweibrücken HRB 1552Z, Steuernummer: 35/657/0427/7

 


 <https://www.youtube.com/watch?v=76OeqWr9kUY&feature=youtu.be>    <https://www.facebook.com/gisbo>   <https://www.instagram.com/gisboalarm/>    <https://twitter.com/GisboGmbh> 

 

 

Von: dorkbox ***@***.***> 
Gesendet: Montag, 22. März 2021 10:58
An: dorkbox/SystemTray ***@***.***>
Cc: St3pp3nw0lf82 ***@***.***>; Author ***@***.***>
Betreff: Re: [dorkbox/SystemTray] Display of Trayicon requires root privileges (#134)

 

Yes, 4.0 will release to maven.

**Comment by dorkbox** [comment]
I expect by the end of the month, provided everything passes the JPMS tests

**Comment by St3pp3nw0lf82** [comment]
Perfect, thanks!

 

Freundliche Grüße aus Zweibrücken

Johannes Cox

Software Developer


  <https://gisbo.de/gisbo_logo_72.jpg> 

	Gisbo Softwareentwicklung
und EDV-Beratung GmbH 
Etzelweg 234
D - 66482 Zweibrücken

	

 


E-Mail: ***@***.***
Web: www.gisbo.de <https://www.gisbo.de/> 

	Tel.: +49 (0) 6332 - 99 790 84
Fax: +49 (0) 6332 - 99 790 80

  _____  



Geschäftsführung: Sabine Eßer und Stella Bayer
Amtsgericht Zweibrücken HRB 1552Z, Steuernummer: 35/657/0427/7

 


 <https://www.youtube.com/watch?v=76OeqWr9kUY&feature=youtu.be>    <https://www.facebook.com/gisbo>   <https://www.instagram.com/gisboalarm/>    <https://twitter.com/GisboGmbh> 

 

 

Von: dorkbox ***@***.***> 
Gesendet: Dienstag, 23. März 2021 12:43
An: dorkbox/SystemTray ***@***.***>
Cc: St3pp3nw0lf82 ***@***.***>; Author ***@***.***>
Betreff: Re: [dorkbox/SystemTray] Display of Trayicon requires root privileges (#134)

 

I expect by the end of the month, provided everything passes the JPMS tests
