### ISSUE TITLE
Unable to use Notify and SystemTray in the same application

### ISSUE THREAD

**Issue by Elvander** [dorkbox/SystemTray#135]
I have an javaFX (java 11) application which needs to send notifications to the user and stay in the tray, but i'm unable to combine both libraries. 

I receive the following error:

`
java.lang.module.ResolutionException: Modules SystemTray and Notify export package dorkbox.util to module hamcrest.core
`

Is there a way to build both packages without the `dorkbox.util` and add this as a dependency? This should resolve the issue...

[Same issue on Notify #21](https://github.com/dorkbox/Notify/issues/21)

**Comment by dorkbox** [comment]
The SystemTray now supports JPMS. Before release, I will also have Notify working with JPMS

**Comment by dorkbox** [comment]
Notify will take a little more time to get ready for JPMS (because the TweenEngine dependency is *not* trivial), so I will close this issue here as SystemTray now supports JPMS.

Work will continue on Notify. See: https://github.com/dorkbox/Notify/issues/21
