### ISSUE TITLE
Open browser doesn't work on WSL 2(Ubuntu 20.04)

### ISSUE THREAD

**Issue by AriaMoradi** [dorkbox/SystemTray#139]
Trying to fix this issue https://github.com/AriaMoradi/Tachidesk/issues/19 
Looks like opening a url with `xdg-open` will open the url on a windows browser window, so the general linux approach should work for WSL.

Also I've seen apps running under WSL being able to open a tray icon on windows without a X11 server but I don't know it works.

**Comment by dorkbox** [comment]
Can you tell me the apps that work under WSL without an X11 server? 

I can investigate this further.

**Comment by AriaMoradi** [comment]
Unfortunately I can't find It again(maybe I was wrong).
But https://github.com/microsoft/WSL/issues/938 is comming?

**Comment by dorkbox** [comment]
I'm going to close this issue, since it's not really a bug with the SystemTray. I did add WSL detection, so at least there's that (should GUI stuff from WSL happen in the future)
