### ISSUE TITLE
2.1: [BUG] Not working with both GTK3 and JavaFX

### ISSUE THREAD

**Issue by kuc** [dorkbox/SystemTray#14]
After adding support for GTK3, I have same bug on startup as when using SWT:

```
(java:2033): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(java:2033): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(java:2033): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

I don't know I you can fix this, so please add option for disabling support for GTK3.

**Comment by dorkbox** [comment]
Hm, I have some ideas on how to do that.

**Comment by kuc** [comment]
Ideas for fix, or ideas for option for disabling use of GTK3? : ]

**Comment by kuc** [comment]
I found that

>It's possible you're hitting a situation where GTK 2 libraries have already been loaded

**Comment by dorkbox** [comment]
For forcing the version of GTK to try.  What happens if you set `GtkSupport.CREATE_EVENT_LOOP = false` ?

**Comment by kuc** [comment]
Same message as above + `INFO  dorkbox.systemTray.SystemTray - Successfully Loaded: App` + segmentation fault for Java process.

So still not better :disappointed:

**Comment by kuc** [comment]
```
Problematic frame:
# C  [libgdk-3.so.0+0x2d970]  gdk_display_manager_get_default_display+0x0
```

**Comment by dorkbox** [comment]
Hm. SWT likely already loads GTK2 - Let me think about detecting if GTK2 is already loaded

**Comment by kuc** [comment]
But I'm not loading SWT on Linux. I tried using it in the past, but same error occurred, so I resigned.

**Comment by dorkbox** [comment]
So you're getting this error on Linux? (ubuntu 15.10?)

**Comment by kuc** [comment]
Just add the option for disabling detection of GTK3 and it will be fine.

>So you're getting this error on Linux? (ubuntu 15.10?)

Yes.

**Comment by kuc** [comment]
Ok, if I remove JavaFX from test app (new library with GTK3 support), then that errors are not shown. But icon in tray is also not visible.

**Comment by dorkbox** [comment]
Is it loading the AppIndicator library?

**Comment by kuc** [comment]
Sorry, my bad - everything works in that case.

**Comment by kuc** [comment]
So the problem arise when using both GTK3 and JavaFX.

**Comment by dorkbox** [comment]
Ahh, it's a JavaFX thing?

**Comment by dorkbox** [comment]
That makes a LOT more sense, because I can detect if JavaFX is in use and switch to GTK2 (there will be warnings if libappindicator1 is not present though).

I'll still add an GTK version override though

**Comment by kuc** [comment]
I think that JavaFX loads some GTK libraries, so it's causing some problems.

>That makes a LOT more sense, because I can detect if JavaFX is in use and switch to GTK2 (there will be warnings if libappindicator1 is not present though).
>I'll still add an GTK version override though

Thanks :smile:

**Comment by kuc** [comment]
As a side note, in the past I tried to force using GTK2 by SWT, but that then caused problems with JavaFX :angry: 

But your library in version `1.12`, when it still used GTK2, was not causing any problems for me. So just conditionally switching to previous behaviour should work :ok:

**Comment by dorkbox** [comment]
I'm guessing now that SWT (GTK2), JavaFX (GTK2), and SystemTray (GTK2/GTK3) -- and they all hate each other. I think I'll change out the event_loop i use, so that will always run (SWT fixed issues they had with nested event loops, which is why i could remove the SWT detection), but it seems that my event loop should always run.

**Comment by dorkbox** [comment]
(that might be a confusing comment...)

**Comment by kuc** [comment]
>SWT (GTK2), JavaFX (GTK2), and SystemTray (GTK2/GTK3) -- and they all hate each other.

Currently, I'm loading SWT conditionally, **only on Windows**. But in that case I'm not loading your library. So forget about SWT :wink: This was only the example of similar error messages.

_(but I still have test program that I can run on Windows, so I could report issue #13 )_

I confirmed that JavaFX uses, and will be using, GTK2. So, if your library is trying to load GTK3, then we see that problems...

**Comment by dorkbox** [comment]
Yea, i'm going to leave out auto-detection, since that is just too tricky. It will just be a boolean you set on startup.

**Comment by kuc** [comment]
:ok: 
And also add documentation _when you want to_ set this, so people will not adding duplicated issues.

**Comment by dorkbox** [comment]
:) yea, i will - just uploaded 2.2 to maven + github, can you try that out?

**Comment by kuc** [comment]
I tried using version `2.3` and it works (even without forcing GTK2 - do you detecting it?), but there still issues with shutting down app. I'm using code:

```
systemTray.shutdown();
Platform.exit(); // JavaFX
```

and then, depending on app and/or that if I started SystemTray before or after starnig JavaFX, gives me that results:

1. calling `systemTray.shutdown()` (from listener thread) just hangs entire app, without even closing opened windows
2. calling `systemTray.shutdown()` (from listener thread) closes app windows, but app still hangs, and there are some error mesages:
```
(java:2716): GLib-CRITICAL **: Source ID 39 was not found when attempting to remove it
(java:2716): GLib-CRITICAL **: Source ID 38 was not found when attempting to remove it
```

Reversing order of calling `systemTray.shutdown()` and `Platform.exit()` doesn't changing much.
Exactly results are semi-randomly, so maybe its' some race condition there.

**Comment by dorkbox** [comment]
I actually found a type leftover from when I was testing -- which might be why it's working now. Shutdown should work  -- i'll investigate

**Comment by kuc** [comment]
Ah, so you accidentally hardcoded use of GTK2 - I see :smiley: 

Shutdown worked correctly in `1.12`, even with JavaFX.

**Comment by dorkbox** [comment]
wow. i just noticed that I didn't use `.shutdown()` in my test example. I think the problem might have been that the dispatch thread was 'interrupting' itself, so anything else in that thread invocation would get ignored.

Try version 2.6 (i just uploaded it to maven + git)

**Comment by dorkbox** [comment]
The reason it would have worked in `1.12` is because i didn't dispatch GTK events to a separate thread. GTK3 specifies that all GTK events **must** be on the same thread (their threading model changed), so that's what I did --- an broke shutdown()... :(  Since it wasn't in my test app, i didn't catch it.

**Comment by dorkbox** [comment]
> Ah, so you accidentally hardcoded use of GTK2 - I see

Yea. Whoops! :(

**Comment by kuc** [comment]
Sorry, no difference with `2.6`. Could you please debug it with JavaFX yourself? I don't have IDE installed on Ubuntu.

Example code for main class below:

```
import javafx.application.Application;

public class Main extends Application {

	@Override
	public void start(Stage primaryStage) throws Exception {

		// insert code for SystemTray here

		primaryStage.show();
	}
}
```

Code for event handler:

```
System.out.println("Before tray shutdown");
systemTray.shutdown();
System.out.println("After tray shutdown, before JavaFX shutdown");
Platform.exit();
System.out.println("After JavaFX shutdown");
```

Exactly behaviour may differ, but application won't close in every case. `"After JavaFX shutdown"` is always printed, sometimes with errors. Check what threads are still active.
Maybe you are terminating some thread needed for JavaFX? :confused:

**Comment by kuc** [comment]
I see in JAVA code that `Platform.exit()` does not block, but only sets flags for other threads to shut down themselves and then returns.

**Comment by dorkbox** [comment]
Yea, I'll debug with javaFX

**Comment by dorkbox** [comment]
wow. All sorts of problems with JavaFX when the system tried to exit. I'm about to go out for the evening, and I don't think I can get this figured out in the next 10 minutes... I'll figure out what is going on tomorrow.

**Comment by dorkbox** [comment]
One thing I noticed -- is that if you close whatever window is open, the system tray stops responding to events.

**Comment by dorkbox** [comment]
At first glance -- it appears that when I shutdown GTK, that also shutsdown the **same** GTK that JavaFX uses. What might be possible (I'll check with this later), is that there is *another* boolean that affects the shutdown procedure. I'm not sure the best way to approach this...

**Comment by dorkbox** [comment]
Because either I shutdown GTK or javaFX shutsdown GTK -- we end up in a `hung` state, where which ever happens fist -- leaves the other unresponsive.

**Comment by kuc** [comment]
>One thing I noticed -- is that if you close whatever window is open, the system tray stops responding to events.

That's excepted behaviour - in JavaFX, by default, closing last window shutdown entire app.

>What might be possible (I'll check with this later), is that there is another boolean that affects the shutdown procedure. I'm not sure the best way to approach this...

I suggest to not adding another boolean, but instead renaming current boolean to something like `JAVAFX_COMPABILITY_MODE`, and leaving the rest of the story hidden as implementation detail.

**Comment by dorkbox** [comment]
Give `2.10` a try. I've done two things.

 - I figured out a pretty reliable way to discover on startup if javaFX has been initialized. JavaFX always starts the GTK main loop, which I now check (and do things differently). This should be 100% reliable, but just in case...
 - Added `JAVAFX_COMPABILITY_MODE` if the autodetection fails.

I also added a `JavaFX test` application as well - the only thing different you'll need to do is call `Platform.exit()` inside of the `quit` callback if you want that to shutdown JavaFX as well. 

If JavaFX main window is closed, the SystemTray will also close. This is necessary since JavaFX kills GTK and it will hang (as previously observed).

**Comment by kuc** [comment]
`2.10`? I tested `2.8` and autodetection of JavaFX and shutdown works flawlessly! Good job :smiley:

What are the new changes in `2.10`?

**Comment by dorkbox** [comment]
Also - I've been testing `SWT`, and so far - no luck.

**Comment by dorkbox** [comment]
`2.10` is the addition of `JAVAFX_COMPABILITY_MODE`. 

A lot of builds are going, trying to get SWT working... Out of curiosity - do you use the SWT systemtray, when you're using SWT?

**Comment by kuc** [comment]
>2.10 is the addition of JAVAFX_COMPABILITY_MODE.

Ok, so I can just update to *newest-newest* version then :wink: 

>do you use the SWT systemtray, when you're using SWT?

Yes, but only system tray component, and only on Windows, when I don't use your library (it still currently does not works on windows anyway, heh). So I don't care about possible incompatibilities.

**Comment by dorkbox** [comment]
> Ok, so I can just update to newest-newest version then

Yea :)

> it still currently does not works on windows anyway
I'll get on that right now, since the idea is for SystemTray to work on everything.

**Comment by dorkbox** [comment]
Alright, `2.11` is release, three changes were made.
 - Windows works again
 - Reverted the checked exceptions back to unchecked exceptions
 - JavaFX is checked to see if it's loaded before adding shutdown hooks (for when javaFX isn't being used, it won't try to initialize javaFX when it adds the hook)

**Comment by dorkbox** [comment]
Arrgh - i test it (it works), push the build to maven and test again in my main app and ... it doesn't work.

**Comment by kuc** [comment]
I'm satisfied with `2.10` release, you don't need to be in a hurry :wink:

**Comment by kuc** [comment]
@dorkbox This AGAIN no longer works on Ubuntu 16.04
Tested with versions 2.12 and 2.20
Both relying on autodetection, and setting compatibility mode manually doesn't work.

**Comment by dorkbox** [comment]
Awesome!! :(

I'll look into it. Sadly, not right away as I'm in the middle of an executable launcher (replacement for java.exe) and context switching is expensive.

**Comment by kuc** [comment]
Ok. I plan to create example test project using [TestFX](https://github.com/TestFX/TestFX) to catch that type of problems earlier in the future.

**Comment by dorkbox** [comment]
Good idea.

**Comment by dorkbox** [comment]
I should probably list a compatibility matrix that this has been tested on.

**Comment by kuc** [comment]
Minimal not working example:

https://github.com/kuc/SystemTray-JavaFXTest

**Comment by dorkbox** [comment]
Just ran some tests in a VM -- it looks like the "normal" (non javaFX) version is working, and I verified that the javaFX version is not.

**Comment by dorkbox** [comment]
Got it working in Gnome 3.20+ (but not if gnome-shell is installed on-top of Unity... that just doesn't work at all, but UbuntuGnome works just fine).

**Comment by dorkbox** [comment]
Still problems with JavaFX (GTK2) on Ubuntu 16.04 (GTK3) -- working those kinks out...

**Comment by dorkbox** [comment]
So it looks like GTK2 on Ubuntu 16.04 is broken in some weird way. GTK2 on xubuntu 16.04 works just fine, GTK3 on Ubuntu/Xubunutu 16.04 works fine -- just GTK2 has issues. This would be why javaFX doesn't work correctly (it uses GTK2)

**Comment by dorkbox** [comment]
Master branch has the latest -- i haven't pushed a build yet, but I think it's ready, and it will likely be tomorrow that I push the build.

**Comment by dorkbox** [comment]
There were some scaling issues with the tray/menu icons. Those issues are getting fixed, and it shouldn't be much longer before I'll have something for testing (it will be downloadable "all-in-one-jars" from my server). If those pass, then I'll push a release.

**Comment by dorkbox** [comment]
3.0 beta is released as a "all-in-one" jar, for a variety of different tray types and configurations. I'm starting a new issue to track the progress for this. I definitely will need help testing in different Linux/Mac/Windows configurations (ie: I have no idea if this works in Windows 10, or the latest MacOsX)

I'm closing this issue and tracking everything in a new one. Please use Issue #22 for all related feedback, problems, etc.
