### ISSUE TITLE
How to build this project referencing the dependent "Utilities" project?

### ISSUE THREAD

**Issue by maztan** [dorkbox/SystemTray#143]
Hello, I will delete this issue once I get an answer. I am trying to contribute to the project but when I try to build it, it complains that it can't find the dependent "Utilities". How do I build this project properly? Thanks

**Comment by dorkbox** [comment]
You can checkout the utilities project, and publish a build to maven local.

All builds, even local ones, need to be signed, so setting this up might be 
a bit of effort.

**Comment by maztan** [comment]
I have no choice really as I have to fix https://github.com/dorkbox/SystemTray/issues/95 for my project.

I have one more question. Is github repository in sync with latest changes?

**Comment by dorkbox** [comment]
I see.

I'm in the middle of fixing jpms problems right now, and github does not 
have the latest.

I will have the 4.0 release at the end of the month.

**Comment by maztan** [comment]
Ok, thank you for the response and for your time (and for creating this great project). I will do what I can to implement a workaround for that issue and wait for the 4.0. Have a great day.

**Comment by maztan** [comment]
Just wanted to report that I have built the Utitlities project and included it in the SystemTray build using this method:
https://stackoverflow.com/a/20700183/478765

**Comment by maztan** [comment]
I had to comment out the lines in build.gradle.kts of SystemTray project:

listOf("win", "linux", "mac").forEach {
            javaFxDeps("org.openjfx:javafx-base:11:${it}")
            javaFxDeps("org.openjfx:javafx-graphics:11:${it}")
            javaFxDeps("org.openjfx:javafx-controls:11:${it}")
        }

When building on windows, only the JavaFX jars for Windows are available. Is this project trying to package javaFx for all platforms?

**Comment by dorkbox** [comment]
Ah!

That works without having to sign anything. Awesome!

**Comment by maztan** [comment]
Any prospects on how long till version 4 release? Just asking.

**Comment by dorkbox** [comment]
Almost done with some regression testing, it should be Monday or Tuesday next week.

**Comment by maztan** [comment]
Many thanks. I can't express enough how your project makes my life easier. Thank you.

**Comment by dorkbox** [comment]
Release is soon, so I'm closing this support issue.
