### ISSUE TITLE
How about a release?

### ISSUE THREAD

**Issue by maztan** [dorkbox/SystemTray#145]
Again, don't want to be a pain but how about a release? We can later have 4.1, 4.2 .... I would just start using it :) I can build it myself naturally. Just let me know how long do you think it will take yet. Thanks

**Comment by dorkbox** [comment]
The release is expected with the next hour.

**Comment by maztan** [comment]
Thanks:)

pt., 9 kwi 2021, 11:51 użytkownik dorkbox ***@***.***>
napisał:

**Comment by dorkbox** [comment]
I know there is a lot of anticipation for release 4.0.

The final build is processing right now, and I will close this issue once the build is released to maven.

**Comment by dorkbox** [comment]
4.0 is now released. It will take a few minutes for sonatype to synchronize the maven repositories.

**Comment by maztan** [comment]
I can find the 4.0 anywhete...
