### ISSUE TITLE
Is it possible to control the "Tray menu" text in Windows task manager

### ISSUE THREAD

**Issue by bdw429s** [dorkbox/SystemTray#147]
When I use SystemTray in some versions of Windows, my java.exe process showed up in Windows Task Manager with a description of "Tray menu".

![image](https://user-images.githubusercontent.com/584009/114241097-42136c00-994e-11eb-8e0e-cea4d0938128.png)

I can't find anywhere I'm setting that text (tho it's entirely likely I just missed it)  Can this text be controlled and how?  I don't get this in Windows 7, but it appears this way in Windows 10 from my brief testing.

Thanks!

~Brad

**Comment by zspitzer** [comment]
Is this it?

https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/ui/swing/TrayPopup.java#L60

**Comment by bdw429s** [comment]
I found that code too, but it was in a method called `TrayPopup()` and was creating a `JDialog` instance which didn't seem like it would relate to the actual menu itself.  If that is ultimately where the text comes from, it looks like it's hard coded.

**Comment by dorkbox** [comment]
Thanks for finding this! The tray name is now passed in and it should have been passed into the `TrayPopup` as well. `SystemTray.get("tray-name-that-you-want")` is how you specify the tray name (which needs to be unique if there are multiple instances of the tray on the same machine)

Thanks for the report.  4.1 is pushed to sonatype, and it will take a while to synchronize all of the maven repositories.
