### ISSUE TITLE
The Utilities project is not updated in maven repos

### ISSUE THREAD

**Issue by maztan** [dorkbox/SystemTray#148]
SystemTray cannot be used from maven as the dependency of correct version of related Utilities is missing.

**Comment by dorkbox** [comment]
I know :(  Completely focused on the SystemTray release I forgot to push it as well.

It was pushed about 10 minutes ago, roughly at the same time as 4.1, so it might take a few more minutes to synchronize on maven.

Sorry about that!

**Comment by maztan** [comment]
No problem. I am thankful that this project even exists. Thanks for fixing
it.

sob., 10 kwi 2021, 10:37 użytkownik dorkbox ***@***.***>
napisał:
