### ISSUE TITLE
Threads/Executor issues in latest version

### ISSUE THREAD

**Issue by viftodi** [dorkbox/SystemTray#156]
Hello,

I am testing the latest version (4.1)

It seems from my investigation that kotlin creates threads/executors for it's coroutines? I assume it creates a number equal to the number of cores?

I have found these threads  that seem to be created by SystemTray?

update-system,5
DefaultDispatcher-worker-1,2 (I have 4 on my machine, name suffix varies of course)

Would it be possible to have some control over them, or for SystemTray to create less threads and with a lower priority?

Another issue is that they don't seem to be cleaned properly, the shutdown hook should stop them, instead of getting them killed ?

**Comment by dorkbox** [comment]
I'll see if they can have a lower priority. They are designed to get killed, but I will make some improvements in that area.

Thanks for the report!

**Comment by dorkbox** [comment]
I added `EventDispatch.THREAD_PRIORITY`, so you can specify which thread priority to use for the SystemTray EventDispatch.

Of note, the threads created either 1) run on a (long) timer, or 2) run once and quit.,

**Comment by dorkbox** [comment]
Fixed in dc2df641
