### ISSUE TITLE
GNOME 40+ support

### ISSUE THREAD

**Issue by guihkx** [dorkbox/SystemTray#157]
On version 4.1:

```
GNOME shell detected, but UNSUPPORTED shell version (40.1). Falling back to GtkStatusIcon.
Please create an issue with as many details as possible.
```

Systray on GNOME still works with the [AppIndicator extension](https://github.com/ubuntu/gnome-shell-extension-appindicator). Also, using an older version of this library (3.16) works just fine too. :)

Thanks!

**Comment by guihkx** [comment]
Hmm, maybe dupe of #146?

**Comment by dorkbox** [comment]
It is very similar, but I will leave this open until the issue is resolved.

Thanks for the report!

**Comment by guihkx** [comment]
It'd be great if an option was added to prevent version checking, just like in version 3.16.

Because I'm running this Java app in a sandboxed environment, where this library won't be able to find the `gnome-shell` binary (or any other binary, really) to do version checking.

Thank you :)

**Comment by m1markus** [comment]
I'm running Fedora 34 with Gnome and have the same issue.

GNOME shell detected, but UNSUPPORTED shell version (40.0). Falling back to GtkStatusIcon. Please create an issue with as many details as possible.

(java:3657): Gtk-ERROR **: 15:40:31.826: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)

If there is a coming pre version with a fix I'm more than willing to test.

Tank you in advance

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 34 (Thirty Four)
Release:	34
Codename:	ThirtyFour

**Comment by dyorgio** [comment]
Version 3.17 works on fedora 34 after install this:
https://extensions.gnome.org/extension/2890/tray-icons-reloaded/

**Comment by Jeansen** [comment]
It seems to work so far for me, but anyway I have something like this on the terminal with Gnome 41.1:

OS is Debian ( bookworm/sid)

```
[JavaFX Application Thread] ERROR dorkbox.systemTray.SystemTray - GNOME shell detected, but UNKNOWN type. This should never happen. Falling back to GtkStatusIcon. Please create an issue with as many details as possible.
19:07:35.071 [JavaFX Application Thread] WARN dorkbox.jna.linux.GtkTheme - Unable to get tray image size. Using fallback: 24

(java:43431): Gdk-WARNING **: 19:07:35.316: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
19:07:35.321 [JavaFX Application Thread] INFO dorkbox.systemTray.SystemTray - Successfully loaded

(java:43431): Gdk-CRITICAL **: 19:07:35.380: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
7414.0
```

**Comment by AriaMoradi** [comment]
```15:56:00.587 [main] ERROR dorkbox.systemTray.SystemTray - GNOME shell detected, but UNKNOWN type. This should never happen. Falling back to GtkStatusIcon. Please create an issue with as many details as possible.```

Running Gnome 42 on Fedora 36

**Comment by dorkbox** [comment]
Fixed.
