### ISSUE TITLE
gdk_screen_get_default hangs

### ISSUE THREAD

**Issue by alanocallaghan** [dorkbox/SystemTray#159]
Trying to run this in an app on Ubuntu 18 and `Gtk2.Gtk2.gdk_screen_get_default();` in `dorkbox.jna.linux` just hangs indefinitely for me

**Comment by dorkbox** [comment]
I’m not able to reproduce this, granted it’s been a while.

![CleanShot 2023-11-22 at 20 33 44](https://github.com/dorkbox/SystemTray/assets/5301521/b6e7a61f-3238-4635-9699-ab7e318048ec)
