### ISSUE TITLE
No menu entry exists for string '...'

### ISSUE THREAD

**Issue by mstrelex** [dorkbox/SystemTray#16]
Hi,

I am wondering if anyone has encountered a similar issue:
Sometimes, when updateMenuEntry is called after addMenuEntry is, an exception occurs (No menu entry exists for string...). Is this some kind of a threading issue ? How can I check that a menu entry indeed exists before trying to update it ?

Thanks.

**Comment by dorkbox** [comment]
Hm, I do see how this could happen, let me think of a way around this race condition.

**Comment by dorkbox** [comment]
I've placed all updates to the SystemTray onto the dispatch thread now and `v2.16` should resolve this issue.

**Comment by mstrelex** [comment]
Thanks.
I will check this right away.
