### ISSUE TITLE
SystemTray.get() fails on MacOS BigSur

### ISSUE THREAD

**Issue by gregorbg** [dorkbox/SystemTray#160]
Hello! I am the maintainer of a JVM application called [TNoodle](https://github.com/thewca/tnoodle). Although I am not a MacOS user myself, one user of the library reported a problem after upgrading `dorkbox.SystemTray` from version `3.17` to `4.1`: https://github.com/thewca/tnoodle/issues/664

After the original report, I contacted other users of the app and at least two of them reported similar issues. The workaround described at https://github.com/dorkbox/SystemTray/issues/153#issuecomment-830584496 seems to solve this crash.

I can contact individual users again if you need more details like JVM or OS versions. Just tell me and I'll be glad to help :)

**Comment by dorkbox** [comment]
Thanks for the info!

There were some issues in fully supporting JPMS, and I'm in having to fix several different support libraries... Once those are done, I'll be able to fix this.

**Comment by Robinbr21** [comment]
is there any update on SystemTray.get()

**Comment by dorkbox** [comment]
Yes. I’m working on fixing it right now (on M1 Monterey, at the moment)

**Comment by dorkbox** [comment]
Sorry this took so long, but it was not easy. I have figured out what exactly is going on, and how to work-around it. macos11 (Big Sur) changed how to create UI elements.
