### ISSUE TITLE
Release asset not found

### ISSUE THREAD

**Issue by stefan-reich** [dorkbox/SystemTray#163]
Not sure how this is possible, but the jar asset in the latest release (3.6) causes a 404. I was hoping not having to compile the library myself...

https://github.com/dorkbox/SystemTray/releases/tag/Release_3.6
https://github.com/dorkbox/SystemTray/releases/download/Release_3.6/SystemTray-3.6.jar

**Comment by viftodi** [comment]
I am pretty sure you can find the jars on the maven repository

**Comment by dorkbox** [comment]
All releases are available here: https://repo1.maven.org/maven2/com/dorkbox/SystemTray/

Please note, these do not include the dependencies, as I do not build a "fat jar".
