### ISSUE TITLE
IllegalAccessError when trying to shutdown

### ISSUE THREAD

**Issue by JavacoderBrian** [dorkbox/SystemTray#164]
08:12:32.462 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - OS: Windows 10
08:12:32.465 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Arch: amd64
08:12:32.465 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 16
08:12:32.465 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is Auto sizing tray/menu? true
08:12:32.466 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is JavaFX detected? true
08:12:32.466 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is SWT detected? false
08:12:32.541 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Java Swing L&F: Metal
08:12:32.541 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
08:12:32.747 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Tray indicator image size: 16
08:12:32.747 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Tray menu image size: 14
08:12:32.963 [JavaFX Application Thread] INFO dorkbox.systemTray.SystemTray - Successfully loaded type: _WindowsNativeTray
08:12:32.963 [JavaFX Application Thread] WARN dorkbox.systemTray.SystemTray - Please disable tooltips, as they are not consistent across all platforms and tray types.
08:12:32.964 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Resizing image to 16 : file:/C:/Users/brian.GREENWEBS/Documents/NetBeansProjects/WilsonsDelivery2/target/classes/opn/greenwebs/transport_train_station.p.666666.32.png
08:12:41.661 [SystemTrayEventDispatch-1] ERROR dorkbox.systemTray.SystemTray - Error calling menu entry Quit click event.
java.lang.IllegalAccessError: class dorkbox.javaFx.JavaFxAccess (in module SwtJavaFx) cannot access class com.sun.javafx.tk.Toolkit (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.tk to module SwtJavaFx
	at SwtJavaFx@1.1/dorkbox.javaFx.JavaFxAccess.isEventThread(JavaFxAccess.java:33)
	at SwtJavaFx@1.1/dorkbox.javaFx.JavaFx.isEventThread(JavaFx.java:146)
	at opn.greenwebs/opn.greenwebs.TestTrayJavaFX.lambda$doJavaFxStuff$13(TestTrayJavaFX.java:223)
	at SystemTray@4.1/dorkbox.systemTray.ui.swing.SwingMenuItem$1.lambda$actionPerformed$0(SwingMenuItem.java:130)
	at SystemTray@4.1/dorkbox.systemTray.util.EventDispatch.lambda$runLater$0(EventDispatch.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by dorkbox** [comment]
This has been fixed. 

Thank you for the info!
