### ISSUE TITLE
Arch KDE requiring Sudo

### ISSUE THREAD

**Issue by sdooweloc** [dorkbox/SystemTray#165]
Hello. I am trying to run a program that utilizes this library. However the program stops when launching from what appears to be the system tray process getting stuck on load. I am able to run the program with sudo and it launches without issue. I also tried running the program on a VM with Arch Gnome as that is on your list of supported combinations. Is there something Arch KDE is missing to cause this to happen? I notice Manjaro KDE is supported on your list but Manjaro is built off of Arch. Is it a dependency or config option that Manjaro has that base Arch does not that could be affecting this? I would appreciate any help you can offer as I daily drive Arch KDE and would prefer to not have to sudo this program. If you need more information please let me know. I know this is kinda barebones but I am willing to provide anything I can to help this be resolved.

**Comment by dorkbox** [comment]
Sadly I cannot fully diagnose all possibilities with regards to Arch, as it is a "build your own DE" compared to Manjaro/Ubuntu/etc.

If this is still an issue with Release 4.2, please let me know and we can take more steps to resolve this.
