### ISSUE TITLE
SystemTray not working in compiled project - there are not enough dependencies

### ISSUE THREAD

**Issue by Stasyanych** [dorkbox/SystemTray#166]
Hello. I have a question about the **SystemTray** version 4.1. When building a project with the **SystemTray** library connected, there is a problem. The library is connected via Gradle
` implementation ("com. dorkbox:SystemTray:$libDorkbox") `
In the IDE startup mode, there are no problems at runtime, and the library works perfectly on three platforms-Windows, macOS or Ubuntu in 20, but if the project is compiled, there are no dependencies in it, namely **Updates**, **Utilities**, **Version**, etc. Because of this, the project simply does not start. The following message is displayed in the log: 
`Caused by: java.lang. ClassNotFoundException: dorkbox.updates.Updates.`
If you separately connect the **Utilities**, **Executor**, **PtopertyLoader**, **SwtJavaFx**, **Updates**, **Version** dependencies as jar files to the project, then the project starts without errors. I suspect that dependencies should be automatically collected when building the project, but for some reason this does not happen.

**Comment by dorkbox** [comment]
I have reworked the gradle build file to fix this.
