### ISSUE TITLE
Changelog for 4.0/4.1?

### ISSUE THREAD

**Issue by theangrydev** [dorkbox/SystemTray#167]
Hi, I was unable to find a changelog for 4.0/4.1. I am currently on 3.17 and want to make sure I understand what was the breaking change from 3.x to 4.x at least.

Is 4.1 intended for production use yet?

Thanks!

**Comment by dorkbox** [comment]
The big 4.x changes was/is the - still work in progress- update to support JPMS. There are issues with JPMS (with regards to SWT) so I've had to make some large architecture changes for the supporting libraries. Essentially, the tooling to support JPMS + multijar builds is terrible, and rife with guessing how things work, and it is a massive pain to figure out.

If you are not experiencing issues, there is no need to update to 4.x yet. The general changes to 4.x is JPMS, more OS supported, and updated libraries.

**Comment by dorkbox** [comment]
Version 4.2 is intended for production with JPMS (along with various OS specific fixes/workarounds)
