### ISSUE TITLE
Failed to run: java.lang.NoClassDefFoundError: dorkbox/systemTray/SystemTray

### ISSUE THREAD

**Issue by mofheu** [dorkbox/SystemTray#168]
It works when I run from the IDE, but when I run the jar it using the "java -jar TestTray-1.0-SNAPSHOT.jar" command, I get the following error message:

"Exception in thread "main" java.lang.NoClassDefFoundError: dorkbox/systemTray/SystemTray"

I'm using Intellij and Gradle with Java 11.

In the file "https://github.com/dorkbox/SystemTray/blob/master/test/dorkbox/TestTray.java" you say "// make sure JNA jar is on the classpath!". How do I do that?

**build.gradle**

`plugins {
    id 'java'
    id 'application'
}

application {
    mainClassName = 'com.example.App'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.example.App'
        )
    }
}

group 'com.example'
version '1.0-SNAPSHOT'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'

    implementation group: 'com.dorkbox', name: 'SystemTray', version: '4.1'

}
`

**TestTray/src/main/java/com/example/App.java**

`package com.example;

import dorkbox.systemTray.SystemTray;

public class App {

    private final SystemTray systemTray;

    public static void main(String[] args) {
        // make sure JNA jar is on the classpath!
        new App();
    }

    public App() {
        //SystemTray.DEBUG = true; // for test apps, we always want to run in debug mode

        this.systemTray = SystemTray.get("SysTrayExample");
        if (systemTray == null) {
            throw new RuntimeException("Unable to load SystemTray!");
        }

        systemTray.setStatus("Initial test only");

    }
}
`

**Comment by dorkbox** [comment]
I have added gradle tasks to create a test jars with all dependencies.
