### ISSUE TITLE
How to change fallback size

### ISSUE THREAD

**Issue by mooziii** [dorkbox/SystemTray#169]
How can i change `GtkTheme.TRAY_IMAGE_SIZE_FALLBACK`? The class GtkTheme doesn't exists

**Comment by dorkbox** [comment]
Fixed: 30611842


Added the following accessible fields,

----

SizeAndScalingLinux.OVERRIDE_MENU_SIZE    (type int, default value '0')
 - Allows overriding of the LINUX system tray MENU size (this is what shows in the system tray).


SizeAndScalingLinux.OVERRIDE_TRAY_SIZE    (type int, default value '0')
 - Allows overriding of the LINX system tray ICON size (this is what shows in the system tray).


SizeAndScalingMacOS.OVERRIDE_MENU_SIZE    (type int, default value '0')
 - Allows overriding of the MACOS system tray MENU size (this is what shows in the system tray).


SizeAndScalingMacOS.OVERRIDE_TRAY_SIZE    (type int, default value '0')
 - Allows overriding of the MACOS system tray ICON size (this is what shows in the system tray).


SizeAndScalingWindows.OVERRIDE_MENU_SIZE    (type int, default value '0')
 - Allows overriding of the WINDOWS system tray MENU size (this is what shows in the system tray).
 
 
SizeAndScalingWindows.OVERRIDE_TRAY_SIZE    (type int, default value '0')
 - Allows overriding of the WINDWOS system tray ICON size (this is what shows in the system tray).
