### ISSUE TITLE
Missing classes in the example

### ISSUE THREAD

**Issue by hrzafer** [dorkbox/SystemTray#174]
I'm using version `4.1`. Can't find version `4.2` in the maven central. And I can't find classes below.

![image](https://user-images.githubusercontent.com/4048197/146850318-bc958af4-cd19-4c20-8177-4b74286836cc.png)

Here is how maven looks. For some reason utilities dependency is omitted.

![image](https://user-images.githubusercontent.com/4048197/146852104-14d71e01-4224-48eb-9a2c-291167a7f82f.png)

**Comment by hrzafer** [comment]
I had to add utilities dependency separately and change it scope to make the project work. 

```xml
      <dependency>
            <groupId>com.dorkbox</groupId>
            <artifactId>SystemTray</artifactId>
            <version>4.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.dorkbox/Utilities -->
        <dependency>
            <groupId>com.dorkbox</groupId>
            <artifactId>Utilities</artifactId>
            <version>1.12</version>
<!--            <scope>runtime</scope>-->
        </dependency>
```

No I'm getting the following exception during runtime:

```
Caused by: java.lang.ClassNotFoundException: dorkbox.util.swing.DefaultPopupMenuUI
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
```

**Comment by dorkbox** [comment]
Sadly, the 4.x releases have problems -- as JPMS has shown to be rather troublesome in getting it work correctly with a multi-jar build. It's quite annoying, so I would recommend the latest 3.x release for now and then switch to the 4.2 release once it's done.

i expect to finish before the end of the year, as I have time for it then.
