### ISSUE TITLE
SysTrayIcon not showing up on Fedora

### ISSUE THREAD

**Issue by mstrelex** [dorkbox/SystemTray#18]
I'm using the same code as on Win/Mac and Xubuntu, however on Fedora the following error appears:

`Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`

I'm on Fedora 4.2.3-300.fc23.x86_64

Any ideas ? Thanks.

**Comment by dorkbox** [comment]
Is this when using the test example, or your own?

**Comment by dorkbox** [comment]
I'll also spin up a Fedora VM when I get a chance to see what's going on

**Comment by mstrelex** [comment]
Same error with test example :(

**Comment by dorkbox** [comment]
ok, good to know.

**Comment by mstrelex** [comment]
Any chance that you can point me to a specific part of the code to try fixing this myself ?

**Comment by dorkbox** [comment]
To help narrow things down, I would put breakpoints in the following places and see when the error is generated.

https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/linux/jna/GtkSupport.java#L49  

https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/linux/AppIndicatorTray.java#L50  

https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/linux/GtkSystemTray.java#L55

https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/linux/GtkMenuEntry.java#L55

https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/linux/GtkMenuEntry.java#L107

https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/linux/GtkMenuEntry.java#L121

**Comment by dorkbox** [comment]
I've reproduced the issue, trying to figure it out.

**Comment by mstrelex** [comment]
Cool, thanks.

**Comment by dorkbox** [comment]
I've fixed the issue, however there are still errors that appear in the console (as you noticed) see issue #19. I haven't a clue why that is happening, and I'm open to suggestions on what might be causing it.

**Comment by dorkbox** [comment]
Try version 2.17

**Comment by mstrelex** [comment]
Much obliged, I will check this at earliest.

**Comment by dorkbox** [comment]
No problem at all, and thanks for your testing.

**Comment by dorkbox** [comment]
@kuc Can you please verify this build works for you, and if you have issues, let me know? I don't expect there to be any issues (I've run a bit of testing myself, but don't have the time to test all variations/distro's). 

The biggest change was to how I dispatch GTK events (I'm now doing it the correct, GTK preferred way) and via my testing it's now (objectively) faster w.r.t. how events are now dispatched (no intermediate threading going on) and more robust w.r.t GTK and GNOME version changes.

**Comment by kuc** [comment]
@dorkbox Ok, I will try to test this release soon...

**Comment by dorkbox** [comment]
@kuc Many thanks :)

**Comment by kuc** [comment]
@dorkbox 

```
Could not find artifact com.dorkbox:SystemTray-Dorkbox-Util:jar:v2.17
```

You put wrong version string in `SystemTray-2.17.pom`:
```
<dependency>
    <groupId>com.dorkbox</groupId>
    <artifactId>SystemTray-Dorkbox-Util</artifactId>
    <version>v2.17</version>
    <scope>COMPILE</scope>
</dependency>
```

It's should be just `<version>2.17</version>`, **without "v"**

**Comment by dorkbox** [comment]
@kuc dangit. Thanks for the feedback -- I'm working on fixing that now.

**Comment by kuc** [comment]
@dorkbox Leave me a message when you will be done with your fixes :wink:

**Comment by mstrelex** [comment]
@kuc @dorkbox - Guys, thanks a lot for you kind help, it’s highly appreciated.

**Comment by dorkbox** [comment]
@kuc the POM should be correct now in `2.18`. There is no longer a fun typo in the maven deployment code...
