### ISSUE TITLE
Release 4.2 missing sources in sources.jar

### ISSUE THREAD

**Issue by pietrygamat** [dorkbox/SystemTray#182]
The sources and javadoc jars seem broken when I download them with maven. They lack actual sources and javadoc, and only contain license files.

**Comment by dorkbox** [comment]
Yes, I've noticed that and have fixed it (it will be fixed in the next release)

**Comment by dorkbox** [comment]
Just pushed 4.2.1, which fixes sources.jar.  There was a bug in the publishing plugin that I use.

I'm very opinionated on this... With access to sources, I find that javadocs are worthless, so I don't bother to compile the HTML for them.
