### ISSUE TITLE
NullPointerException when scaling on Windows 11

### ISSUE THREAD

**Issue by zheng-wang** [dorkbox/SystemTray#186]
First of all, great library!

I saw the same issue as https://github.com/dorkbox/SystemTray/issues/107 with the latest Windows 11 version (using dorkbox SystemTray 4.2.1). The exception details were mostly the same, with a bit difference, like following

```
dorkbox.jna.windows.WindowsEventDispatch: Error during listener execution.
! java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "s" is null
! at dorkbox.jna.windows.structs.NOTIFYICONDATA.setTooltip(NOTIFYICONDATA.java:70)
! at dorkbox.systemTray.ui.swing._WindowsNativeTray.show(_WindowsNativeTray.java:278)
! at dorkbox.systemTray.ui.swing._WindowsNativeTray.access$700(_WindowsNativeTray.java:61)
! at dorkbox.systemTray.ui.swing._WindowsNativeTray$2.run(_WindowsNativeTray.java:181)
! at dorkbox.jna.windows.WindowsEventDispatch$1.callback(WindowsEventDispatch.java:166)
! at dorkbox.jna.windows.User32_64.GetMessage(Native Method)
! at dorkbox.jna.windows.WindowsEventDispatch.run(WindowsEventDispatch.java:190)
! at java.base/java.lang.Thread.run(Thread.java:833)
```

Also, when the NullPointerException occurred, the system tray disappeared.

The only workaround I found was to set a tooltip on the system tray:

`systemTray.setTooltip("My App");`

but this resulted in a warning log:

`dorkbox.systemTray.SystemTray: Please disable tooltips, as they are not consistent across all platforms and tray types.`

Not a blocker for me, as the workaround is simple. But it would be great if the issue can be fixed in SystemTray library, so that scaling on Windows doesn't cause NullPointerException.

**Comment by dorkbox** [comment]
how interesting.

I’ll look into this before the next release.

**Comment by dorkbox** [comment]
Fixed.
