### ISSUE TITLE
Clean approach to use Gtk to display icons next to menu items

### ISSUE THREAD

**Issue by sschuberth** [dorkbox/SystemTray#187]
I'm just wondering whether the hack described [here](https://github.com/dorkbox/SystemTray/blob/d9d26174b6a1f5c075ba38c0eb8481d31a4081d0/src/dorkbox/systemTray/ui/gtk/_AppIndicatorNativeTray.java#L39-L43) is still required, or whether it could im implemented by now as described [here](https://docs.gtk.org/gtk3/class.ImageMenuItem.html):

> If you want to display an icon in a menu item, you should use GtkMenuItem and pack a GtkBox with a GtkImage and a GtkLabel instead.

**Comment by dorkbox** [comment]
Ah, sadly it all depends on your OS.

AppIndicators: No, Canonical unilaterally decided not to support icons - and there is nothing (I’m aware of) that can be done to add them.

GtkMenuItems: Yes, icons work (and this is how I do it).

And sadly, some OSes only support AppIndicators, and not GtkMenuItems.
