### ISSUE TITLE
SystemTray initialization hangs for 60 seconds  

### ISSUE THREAD

**Issue by pfitzsimmons** [dorkbox/SystemTray#190]
I am running SystemTray on PopOS 22.04 ((which is modified Ubuntu) / Gnome 42.5 / X11. When I call SystemTray.get("MyTray"), the call hangs for 60 seconds before returning correctly. I used the debugger to figure out where it is blocking, and it is at this location:

`dorkbox/os/Os.kt` line 979: `var contains = execute("ps", "x").contains("gnome-shell")` 

This method was called by:

`dorkbox/systemTray/util/AutoDetectTrayType.java`  line 133: `OS.DesktopEnv.Env de = OS.DesktopEnv.INSTANCE.getEnv();`

Here is the stack trace:

```
invoke:979, OS$DesktopEnv$isGnome$2 (dorkbox.os)
invoke:970, OS$DesktopEnv$isGnome$2 (dorkbox.os)
lambda 'synchronized' in 'value':74, SynchronizedLazyImpl (kotlin)
getValue:69, SynchronizedLazyImpl (kotlin)
isGnome:970, OS$DesktopEnv (dorkbox.os)
invoke:1192, OS$DesktopEnv$env$2 (dorkbox.os)
invoke:1176, OS$DesktopEnv$env$2 (dorkbox.os)
lambda 'synchronized' in 'value':74, SynchronizedLazyImpl (kotlin)
getValue:69, SynchronizedLazyImpl (kotlin)
getEnv:1176, OS$DesktopEnv (dorkbox.os)
<clinit>:1229, OS$DesktopEnv (dorkbox.os)
get:133, AutoDetectTrayType (dorkbox.systemTray.util)
get:541, SystemTray (dorkbox.systemTray)

```

I think I know what the bug is. In `dorkbox/os/OS.kt#execute`, if the output of the command is greater than the buffer size, the process will hang waiting for the caller to read all the output produced. I believe the fix is that the "waitFor" call that waits for the process to complete should be called AFTER the readText() call, since the process will wait for its output to be read before it exits. (There is more discussion of this type of issue here https://stackoverflow.com/questions/3285408/java-processbuilder-resultant-process-hangs )

As a workaround, in my calling code, I am able to set the FORCE_GTK2 variable which avoids the call altogether:

```
        if ("pop:GNOME".equals(System.getenv("XDG_CURRENT_DESKTOP"))) {
            SystemTray.FORCE_TRAY_TYPE = SystemTray.TrayType.AppIndicator;
            SystemTray.FORCE_GTK2 = true;
            SizeAndScaling.TRAY_SIZE = 16;
        }
```

**Comment by Nohus** [comment]
> I believe the fix is that the "waitFor" call that waits for the process to complete should be called AFTER the readText()

That indeed solves the issue, I did that in my local fork.
