### ISSUE TITLE
slf4j

### ISSUE THREAD

**Issue by gmseed** [dorkbox/SystemTray#191]
It would be nice if there were some notes about what is required at runtime with regards to slf4j. 

I have included the Maven dependency and it builds fine but faced with a runtime issue relating to slf4j.

There are dozens of slf4j libs and jars and which one(s) to choose and which version?

**Comment by dorkbox** [comment]
You can see the dependency list here:
https://github.com/dorkbox/SystemTray/blob/ea23b1da81bd540c4d28ed718e1be19a77173d2e/build.gradle.kts#L182

Everyone has different requirments, but this should help you out:
``` 
 // note: this has support for JPMS, so it's required
    api("org.slf4j:slf4j-api:1.8.0-beta4")  // java 8
//    api("org.slf4j:slf4j-api:2.0.7") // java 11 only


    val logbackVer = "1.3.5" // java 8
//    val logbackVer = "1.4.5" // java 11 only
//    api("ch.qos.logback:logback-classic:$logbackVer”)
```
