### ISSUE TITLE
Unable to get Version correctly due to system encoding

### ISSUE THREAD

**Issue by smallclover** [dorkbox/SystemTray#194]
My Windows 11 encoding is GBK, So executing the command [ver] cannot get the Version correctly

![image](https://github.com/dorkbox/SystemTray/assets/10950966/ee69bb77-811c-4874-b20c-7a7823e8c5c6)

**Comment by dorkbox** [comment]
I honestly haven’t any idea how to get the version info for GBK encoded installs. 

Would you be able to investigate this further? Specifically, maybe there is a CLI command similar that can get this?

**Comment by dorkbox** [comment]
Just had an idea that will fix this pretty easily.. I’ll just parse for `Version` as before, but if it’s not found (which would be an encoding issue), i’ll use the first numbers available.

**Comment by dorkbox** [comment]
(fixed)

**Comment by smallclover** [comment]
> I honestly haven’t any idea how to get the version info for GBK encoded installs.
> 
> Would you be able to investigate this further? Specifically, maybe there is a CLI command similar that can get this?

After my multiple attempts, maybe you can try this method，No matter what encoding, first convert to UTF8

``` kotlin
                    val output = execute("cmd.exe", "/c", "chcp 65001 | ver | chcp | ver")
````

**Comment by smallclover** [comment]
> (fixed)

THX
