### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Matsv** [dorkbox/SystemTray#20]
Hello,

I had some features in mind that could be useful

- [ ] Submenu's
- [ ] Possibility to add empty lines to keep things organized / to add non-clickable texts.

Thanks for making this library, it's really helpful because the default looks like windows 2003 on Linux :smile:

**Comment by dorkbox** [comment]
You're welcome!

Those are some good ideas which I have personally thought about adding as well. Maybe even an actual "line" is possible?

Time is always the enemy on public projects; I have a very full schedule, and before I do these things I need to finish up some work on the MBassador project, so it will be a little while before they are implemented. 

If you wanted to contribute something (something simple and easy if fine with me), I'd happily add it.

**Comment by Matsv** [comment]
I'll try to work on it when I have time. The only thing is, I don't have a Windows workspace set up at the moment. What libraries do you use?

**Comment by dorkbox** [comment]
[JNA](https://github.com/java-native-access/jna) is the only thing you'll need, but it is only necessary for Linux since Windows/Mac use the "Java" default one with a custom popup-menu, which is just a JPopupMenu.

**Comment by jechaviz** [comment]
Is there a way you could add support for simple tooltip? Anything like systemTray.info("Message"); systemTray.warning("Message"); systemTray.error("Message");
Thank you in advance.

**Comment by kuc** [comment]
@jechaviz See this quote from README:

>**We also cater to the lowest-common-denominator** when it comes to system-tray/indicator functionality, and there are some features that we don't support. Specifically: tooltips. Rather a stupid decision, IMHO, but for more information why, ask Mark Shuttleworth. See: https://bugs.launchpad.net/indicator-application/+bug/527458/comments/12

**Comment by dorkbox** [comment]
@jechaviz you can also use the [Notify](https://github.com/dorkbox/Notify/) project to display notifications next to the system tray. They are not attached to anything in particular so you can place them anywhere you like. It's not exactly the same thing as a system tray tooltip, but it's the closest one can get given the restrictions on system tray events.

**Comment by tresf** [comment]
> Windows/Mac use the "Java" default one with a custom popup-menu, which is just a JPopupMenu.

FYI, I've had a [lot of problems](http://stackoverflow.com/questions/16378886/java-trayicon-right-click-disabled-on-mac-osx/35919788#35919788) with the `JPopupMenu` on Mac, so I actually wrote a small [AWT wrapper](https://github.com/qzind/tray/blob/2.0/src/qz/ui/tray/AWTMenuWrapper.java).  AWT [looks perfect](https://cloud.githubusercontent.com/assets/6345473/18461959/ae267d50-794c-11e6-8444-f9e81dda3d4e.png) on Mac, just suffers the dead right-click bug.

**Comment by dorkbox** [comment]
Nice!  Would you be able to see if the 3.0 beta (available in issue #22) works the way it should?  Also, I have "baked in" configurations for testing, and auto-detect should always work the way you want, but... can you also see what happens with the GtkStatusIcon version (does it suffer from the dead right-click bug?)

**Comment by tresf** [comment]
> Nice! Would you be able to see if the 3.0 beta (available in issue #22) works the way it should? Also, I have "baked in" configurations for testing, and auto-detect should always work the way you want, but... can you also see what happens with the GtkStatusIcon version (does it suffer from the dead right-click bug?)

In my tests against `SystemTray_normal.jar` + MacOS 10.11 (El Capitan):
 * Both left click as well as right click work flawlessly.
 * The menu does not hang, it does not linger behind after the mouse have been moved off of it.

![screen shot 2016-09-25 at 10 38 22 pm](https://cloud.githubusercontent.com/assets/6345473/18821059/cea86bdc-8370-11e6-9683-4051cf836b05.png)

**Comment by tresf** [comment]
**Edit:** `forceGtkStatusIcon` passes too, as does OSX 10.7 Lion.  Updated post.

**Comment by dorkbox** [comment]
Awesome, thank you for testing this!

**Comment by dorkbox** [comment]
Any possibility you can also verify the javaFX and SWT versions?

**Comment by tresf** [comment]
Windows 10 x64 looks good with exception of the large icon size when run on hi-dpi display.

![image](https://cloud.githubusercontent.com/assets/6345473/18841917/528bea26-83e1-11e6-9cc1-ef094e5d1401.png)

Off-topic, but how did you fix the actual tray icon scaling?  JNI?


> Any possibility you can also verify the javaFX and SWT versions?
> EDIT: just the "normal" test is sufficient.

Sure however I find these statements to be contradictory. Can you please be more specific?

You have the following unit tests:

```
SystemTray_autodetect/	
    SystemTray_javaFX.jar
    SystemTray_normal.jar	
    SystemTray_swt.jar	
SystemTray_forceAppIndicator/
    SystemTray_javaFX.jar
    SystemTray_normal.jar	
    SystemTray_swt.jar	
SystemTray_forceGtkStatusIcon/
    SystemTray_javaFX.jar
    SystemTray_normal.jar	
    SystemTray_swt.jar	
SystemTray_forceSwing/
    SystemTray_javaFX.jar
    SystemTray_normal.jar	
    SystemTray_swt.jar	
```

**Comment by dorkbox** [comment]
by "normal", i meant just using the autoDdetect directory --- sorry for the confusion.  

As per fixing the scaling issue on windows, that was a tricky deal. I'm doing in-memory bytecode modification of the windows tray class at runtime and then injecting it into the bootstrap classloader.

**Comment by dorkbox** [comment]
I'll fix the menu icon size... whoops! I forgot windows doesn't auto-scale those.

**Comment by dorkbox** [comment]
Submenu's and separators have been added to beta 3.0. Please see the (oldest) entry for appropriate beta jars for testing.
