### ISSUE TITLE
"sun.awt.CGraphicsDevice" dependency not available when using OpenJDK 17 Java

### ISSUE THREAD

**Issue by hartmut27** [dorkbox/SystemTray#201]
On a Manjaro Xfce machine, I wanted to run the test program

`SystemTray/test/dorkbox/TestTray.java`

```
/home/hape/SystemTray/src/dorkbox/systemTray/util/SizeAndScalingMacOS.java:22: error: cannot find symbol
import sun.awt.CGraphicsDevice;
              ^
  symbol:   class CGraphicsDevice
  location: package sun.awt
```

it seems this dependency is only used in MacOS logic implementation, so for testing reasons and since I am not using MacOS I commented out those usages temporarily and then the test could be run with success.

Is there anything I have overlooked? 
Release 4.4. version of the source had not imported "sun.awt.CGraphicsDevice" as far as I could see (SizeAndScalingMacOS.java).
Is openJDK support dropped accidentally?

**Comment by dorkbox** [comment]
How are you running the test?

`SizeAndScalingMacOS.java` is only called when MacOS is detected, and that class exists on MacOS.

I’ll double check with Manjaro Xfce. Can you provide me the exact details of the OS?

**Comment by dorkbox** [comment]
Ah, I see what is going on. 

Thanks for the info - i’ll have a fix shortly!

**Comment by dorkbox** [comment]
Can you give this another try?

If there are errors, can you get me a full stack trace?

**Comment by dorkbox** [comment]
Please open another issue if you still encounter this.
