### ISSUE TITLE
Tip for the tray menu on Windows

### ISSUE THREAD

**Issue by Nohus** [dorkbox/SystemTray#204]
By default the library will produce a Java-looking menu that looks very off from native tray menus on Windows (as seen in the Readme).
However if you call `UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())`, the tray menu will look the same as native menus.

I think it would be useful to add that to the Readme. With just that 1 line the result is much better. (Or add that to the library itself, though I think just documenting it is enough.)

| Before call | After call |
|--------|--------|
| ![Capture](https://github.com/dorkbox/SystemTray/assets/11064768/4d2041cb-4905-4467-856b-f663f25eb8a6)| ![Capture](https://github.com/dorkbox/SystemTray/assets/11064768/c39c78c3-15fc-40b5-a8e2-6dd9b4bf904e)|

**Comment by dorkbox** [comment]
Oh great find!

I’ll absolutely do that for windows, and add this to the docs. I appreciate it.

**Comment by Nohus** [comment]
The reason I'm not sure about adding it to the library itself is that it may override the theme if someone is already setting another one for their app. But as long as it can be turned off it could be a good default.

**Comment by dorkbox** [comment]
It is only changed if the L&F is the default one (Metal) and the `WindowsNative` tray type is specified.

**Comment by dorkbox** [comment]
continued: If someone wants to customize the L&F, by changing it from `Metal`, it would be changed. Alternatively, if one wanted the “Java” L&F, they could  would specify the `Swing` tray type or set `AUTO_FIX_INCONSISTENCIES = false;`

I’ll think about this a little more, but this is how I setup quite a bit of other `tweaks` for the systemtray.

**Comment by dorkbox** [comment]
I’m closing this, as this is now done —  but if you think of somethin, or really object to the implementation details — please open a new issue)
