### ISSUE TITLE
Initialize system tray error without jar package

### ISSUE THREAD

**Issue by asfdnkw** [dorkbox/SystemTray#213]
Hello!
I am not using the Gradle project and need to manually download the jar package myself. When I initialized the system tray, SystemTray=SystemTray. get();
The result obtained is always null。

I am running in the Ubantu2204 environment. Only with this line of code, the result obtained is null

**Comment by gmseed** [comment]
Hi

What I typically do when I want the jar is to find the project on the Maven Repo:

https://mvnrepository.com/artifact/com.dorkbox/SystemTray

and then select the latest 4.4 version:

https://mvnrepository.com/artifact/com.dorkbox/SystemTray/4.4

In the "Files" section you'll see a link "View All".

This will take you to the project jars.

**Comment by asfdnkw** [comment]
Yes, your answer has been very helpful to me. I have another question. When I run the test code on GitHub, run SystemTray=SystemTray. get();
This line of code can obtain the tray.
When I tried to run this line of code in my own project, I did get null.
I got the difference between the two through debag. Int loadedGtkVersion=GtkCheck. getLoadedGtkVersion () in the testing code SystemTray on GitHub;
The result obtained is 3
Then the project I ran myself obtained an int loadedGtkVersion=GtkCheck. getLoadedGtkVersion ();
The result is 0
I don't know much about it. Can you give me some help. Thank you.



glp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dorkbox/SystemTray"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月16日(星期二) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dorkbox/SystemTray] Initialize system tray error without jar package (Issue #213)





 
Hi
 What I typically do when I want the jar is to find the project on the Maven Repo:
 
https://mvnrepository.com/artifact/com.dorkbox/SystemTray
 
and then select the latest 4.4 version:
 
https://mvnrepository.com/artifact/com.dorkbox/SystemTray/4.4
 
In the "Files" section you'll see a link "View All"
 
This will take you to the project jars.
