### ISSUE TITLE
SystemTray systemTray = SystemTray.get(); The result obtained is null

### ISSUE THREAD

**Issue by asfdnkw** [dorkbox/SystemTray#215]
In my Java project, I introduced the jar packages required for the tray. And then only called
SystemTray systemTray = SystemTray.get();  This line of code. The result obtained is null.
Here is my code's debag process
![123456](https://github.com/user-attachments/assets/f372b8a5-4799-476b-b9bb-584187d26428)

![2222](https://github.com/user-attachments/assets/7fce9273-ac32-4f58-b244-ba4599fd9ae1)

**Comment by westboy** [comment]
which operating system are you using?

**Comment by asfdnkw** [comment]
I am using ubantu22.04. I have resolved this issue and wish you a happy life as well
