### ISSUE TITLE
Beta 3.0 mac support

### ISSUE THREAD

**Issue by dorkbox** [dorkbox/SystemTray#23]
Support feedback/thread for javaFX working on mac

**Comment by tresf** [comment]
Task (from a Mac):

* Download and extract [SystemTray_v2.20_src.zip](https://files2.dorkbox.com/SystemTray_autodetect/SystemTray_v2.20_src.zip)
* Open project with IntelliJ IDEA
* Put a breakpoint on `SystemTray.get()` in `TestTrayJavaFX.java`
* Run `TestTrayJavaFX` in debug-run mode ![image](https://cloud.githubusercontent.com/assets/6345473/19196544/fc45e95e-8c83-11e6-98cb-9bf8d362363e.png)
* Step debug through `SystemTray.get()`, to see when the JVM dies.

@klabarge if you can get to this over the weekend, let me know.

@dorkbox please correct this post if I've made any typos.

**Comment by dorkbox** [comment]
@tresf @klabarge Thanks for checking into this, as I greatly appreciate it. Edited download file (correct one is SystemTray_project.zip)

**Comment by tresf** [comment]
@dorkbox the only crash I'm getting on a Native MacOS 10.11 Machine is `NullPointerException` at `resizeAndCache`, which seems to be a standard NPE bug.

If running the same code from a MacOS 10.11 VM, the entire JVM crashes.

```java
public static synchronized
    File resizeAndCache(final int size, final URL imageUrl) {
        String cacheName = size + "_" + imageUrl.getPath();
```

I patched this by hard-coding the embedding image URLs and then JavaFX scene loaded but hangs indefinitely like it's waiting for something.  It's just a blank scene with a spinning pinwheel of death.

The line I believe that is blocking is:

```java
this.systemTray.addEntry("Green Mail", GREEN_MAIL, callbackGreen);
```

If I wrap these into a separate thread, the "Hello world" button shows, otherwise it never makes it there.

**Comment by dorkbox** [comment]
Yup, I was having the exact same problem testing in a MacOS VM (mine was in 10.9)...

> the only crash I'm getting on a Native MacOS 10.11 Machine is NullPointerException at resizeAndCache, which seems to be a standard NPE bug.

> If I wrap these this.foo lines into a separate thread, the "Hello world" button shows, otherwise it never makes it there.

Ah... it is as I suspected then. There are issues w.r.t. which thread it's on (JavaFX on mac start's on a different thread than win/linux).  I've got mac hadware incoming so I can figure this out without resorting to "blind" fixes. 

I suspect next week I'll be able to have something, meanwhile I'll finish up the API and a few remaining bugs. Right now i've got `SystemTray.get()` for the swingUI menus, and `SystemTray.getNative()` for nativeUI menus.  

@tresf W.r.t. nativeUI menus -- do you think I should use the Windows nativeUI as well? Then, you would conditional out windows with `SystemTray.get()` and everything else would be `SystemTray.getNative()`?  

The reason I ask is because the Windows native menu looks absolutely terrible (zero theme support iirc), and the behavior of the swingUI is magnitudes better. The down side is that it's not native and thus, the notion of `SystemTray.getNative()` is corrupted...

**Comment by tresf** [comment]
> @tresf W.r.t. nativeUI menus -- do you think I should use the Windows nativeUI as well? Then, you would conditional out windows with SystemTray.get() and everything else would be SystemTray.getNative()?

To be fair, MacOS has built native-ish menu support through AWT and Linux is going to receive native support through your library.  Windows wouldn't fall into that category unless you hacked the Win32 API because as you've said the default AWT support is worse than Swing.  I would vote that you simply echo a warning that native menu support isn't supported, or choose a name which is better suited for that particular function.

So yes, I agree, AWT is garbage.  If someone wants an AWT wrapper, they can explicitly request that.  My code is all swing, so the JPopupMenu is what I use for all actions, artwork, etc.  It accepts action listeners that can be bound to JButtons, etc.   Hope that helps.

**Comment by tresf** [comment]
I'll clarify a bit... 

My code (which influences my use-cases) is all swing, so the JPopupMenu is what I use for all actions, artwork, etc.  Swing works seamlessly with other swing interfaces (JComponent, etc) so it just feels more natural in code versus AWT logic.

When I searched around the internet for this problem, the `JXTrayIcon` was the best I could find, so that became the interface I coded against.  All my code extends `JXTrayIcon`; It was a good unofficial standard to use and one that assumed the `JPopupMenu` was being used as the container for all menus and menu items..  That would be my baseline for this particular feature, personally.

As you add more features like widget support (something I see as increasingly popular) it is of less interest to me currently as just basic tray support is so flawed in Java that having nice toggle buttons, sliders etc is just too far down the wish list. 👍

**Comment by dorkbox** [comment]
I'll have it setup to wrap JPopupMenu, so if that is already setup, it'll be able to import it. (as a backward compatibility feature)

**Comment by tresf** [comment]
Ok, ours extends `JPopupMenu`, but we can adjust as needed.  Extending `JPopupMenu` has the advantage of overriding the add/remove on AWT menus, etc.  We haven't written the wrapper to add/remove but can certainly help with that portion if needed.

**Comment by dorkbox** [comment]
Ahhhh. I might do that.

**Comment by dorkbox** [comment]
>  Extending JPopupMenu has the advantage of overriding the add/remove on AWT menus, etc.

This is why I might do that + then people don't have to learn a new API. I will likely override setMnemonic(char) as well --- my god it's annoying having to use VKey instead of just the char. Java is UTF-16 (so I wrote a nifty converter to the VKey from a char, to support java 6)!

**Comment by dorkbox** [comment]
There are likely issues with how the right click is intercepting + changing the focus for the SystemTray + menu... See issue #22, this [comment](https://github.com/dorkbox/SystemTray/issues/22#issuecomment-254093430).

**Comment by dorkbox** [comment]
I have a mac now, working on getting my dev environment setup + configured, then I will figure out what's going on.

**Comment by dorkbox** [comment]
I have discovered what is going on with macOS and appears to only be an issue with java7.  Specifically, the problem is how javaFX + AWT are initialized. I know what needs to be done, but I haven't figure out exactly how to do it yet.

I will keep you updated.

**Comment by dorkbox** [comment]
MacOSX should be completely working now. New beta jars, `get()` & `getNative()` versions are on the server.

There are issues with JavaFX (Java7 only) that can only be fixed via System Properties. Specifically `-Djavafx.macosx.embedded=true` needs to be set. This can be done via System.setProperty(), as long as it happens before javaFX is used.

**Comment by tresf** [comment]
@dorkbox can you provide some more information on the `-Djavafx.macosx.embedded=true` command?  It's quite off-topic but to speak on behalf of those of us battling unrelated JavaFX issues, any `JAVA_OPTS` i related to JavaFX would be great to know.

**Comment by dorkbox** [comment]
@tresf. Sure. `-Djavafx.macosx.embedded=true` is required because on MacOSX, one cannot mix AWT+JavaFX unless that property is specified. Even with that specified, things are still a little tricky, since AWT must be initialized **before** javaFX, and [this is how I specifically solved the problem](https://github.com/dorkbox/SystemTray/blob/e24e42e4d9585e91dd6f30e597649fddd73b031b/test/dorkbox/TestTrayJavaFX.java#L77) and would recommend something similar.

See https://bugs.openjdk.java.net/browse/JDK-8116017  and  https://bugs.openjdk.java.net/browse/JDK-8118714   for a little more insight. 

So you are aware, this was resolved in Java8 and some versions of Java7, but from my experience, 7 didn't work (and this was with the last public release of Oracle's 7). Additionally, Swing+SWT also is incompatible on MacOSX, but that is a different issue entirely.

**Comment by dorkbox** [comment]
@tresf If you can verify MacOSX is working correctly for you (javaFX and the mouse-click bug), I'd like to close this issue.

**Comment by tresf** [comment]
Minor: I noticed the right-click uses some sort of click/release timer.  This is only slightly noticeable as the left-click draws the menu immediately however the right click is slightly delayed.  If one holds right-click for longer than 1 second, the menu shows and disappears.  With the right timing this behaves as is if it disappears just as release is pressed.  When compared to other tray icons, the behavior is to draw the menu immediately and allow click of highlighted menu items on release.  Again, minor but worth noting.

Mac test results:

**getNative/Normal:**
* ✅  **PASS:** macOS 10.7, Java 1.8.0 u45 [[screenshot](https://cloud.githubusercontent.com/assets/6345473/21166072/38505598-c171-11e6-95dd-d6760c08357b.png)] VM
* ✅  **PASS:** macOS 10.8, Java 1.8.0 u111 [[screenshot](https://cloud.githubusercontent.com/assets/6345473/21166392/5c87630a-c173-11e6-8914-5850c257f5bd.png)] VM
* ✅  **PASS:** macOS 10.11, Java 1.8.0 u77 [[screenshot](https://cloud.githubusercontent.com/assets/6345473/21165998/c4419b08-c170-11e6-8689-cf1a72e6186c.png)] Physical




**getNative/JavaFX:**
* ⚠️  **FAIL:** macOS 10.7, Java 1.8.0 u45 [[known issue](https://github.com/dorkbox/SystemTray/issues/23#issuecomment-253107459)] VM
* ⚠️  **FAIL:** macOS 10.8, Java 1.8.0 u111 [[known issue](https://github.com/dorkbox/SystemTray/issues/23#issuecomment-253107459)] VM
* ✅  **PASS:** macOS 10.11, Java 1.8.0 u77 [[screenshot](https://cloud.githubusercontent.com/assets/6345473/21166215/1a10deb2-c172-11e6-8cd8-bf60830e60e5.png)] Physical

**Comment by dorkbox** [comment]
@tresf Thanks for the feedback, I'm glad it's now verified as working --- now it can be optimized...  You're right about it being on a click/release timer -- I'm not sure how to handle right-click --- it's currently on `mouse-down`, should it be on `mouse up` instead that the menu is shown (which would be different than the normal menus, IIRC) or... ???

I can also shorten (and make it an option to change as a property) the click/release timer delay, so to hide the effect of the click/release timer. Unfortunately, a delay is required -- I'm just not certain on the duration.

**Comment by tresf** [comment]
>  it's currently on mouse-down, should it be on mouse up instead that the menu is shown 

I think you typed this backwards.  MacOS shows the menu on mouse-down and yours shows it on mouse-up.

> I can also shorten (and make it an option to change as a property) the click/release timer delay, so to hide the effect of the click/release timer. 

It's immaterial.  The fact that it works is the major win.  If we can mimic the native behavior great, if not, great will become the enemy of good. 😉

**Comment by dorkbox** [comment]
RC1 jars are on my server, and it should now mimic the native mouse behavior (all it took was to slightly tweak the timer/mouse events).

I'm doing some issue cleanup to prep for release, so in the unlikely event there are still issues, please create a new one.
