### ISSUE TITLE
How can I use version 3.0 in my code?

### ISSUE THREAD

**Issue by ashyon** [dorkbox/SystemTray#25]
I'd like to use the git version, but it seems to be missing some util libraries?

**Comment by dorkbox** [comment]
If you want to get started immediately, you can get the latest beta jar [here](https://files2.dorkbox.com/SystemTray_autodetect/SystemTray_v2.20_normal.jar) along with the source [here](https://files2.dorkbox.com/SystemTray_autodetect/SystemTray_v2.20_src.zip)

This has everything included, ie: a fat jar, so no external dependencies.  Just be warned, it's not finished (specifically `SystemTray.getNative()` is not complete), and there will likely be some small changes once it's finished.

I just pushed this to my server, and it is currently tracking 100% what is on github.

Once 3.0 is released, you'll need to pull in the dependencies separately (either manually or via maven/gradle/etc), and if necessary - make small API adjustments where needed.
