### ISSUE TITLE
Menu looks like crap (Gnome Shell, JavaFX)

### ISSUE THREAD

**Issue by ashyon** [dorkbox/SystemTray#28]
![screenshot from 2016-10-12 12-33-33](https://cloud.githubusercontent.com/assets/9281956/19319042/007bbe1a-9079-11e6-80ea-988a29ad217f.png)

**Comment by dorkbox** [comment]
That's the native menu. Use `SystemTray.get()` instead of `SystemTray.getNative()`

**Comment by dorkbox** [comment]
(and yes, it looks like crap. They all look like crap except the native Apple menus... go figure)

**Comment by ashyon** [comment]
Ah, I see the problem. That's not the native menu. I needed to use SystemTray.getNative().

**Comment by dorkbox** [comment]
getNative() == crap (except on windows). This is only here for legacy menus.
get() == nice Swing UI (not crap) on all OS's

**Comment by ashyon** [comment]
getNative() on gnome 3:
![screenshot from 2016-10-12 12-50-31](https://cloud.githubusercontent.com/assets/9281956/19319389/b5a5b970-907a-11e6-883c-02fcf1480b0f.png)

get() on gnome 3:
![screenshot from 2016-10-12 12-33-33](https://cloud.githubusercontent.com/assets/9281956/19319388/b59e3c4a-907a-11e6-86cd-fa153f4a9a1c.png)

**Comment by dorkbox** [comment]
Hm. I do suppose the swing one looks a little bland. TBH it does look like crap on your system, I'm not sure why. It looks a lot better on mine (Still a simple look&feel, but not terrible at all)

**Comment by dorkbox** [comment]
I'll reopen this to make sure I see what it's like on Arch before I release.

**Comment by ashyon** [comment]
It really depends on what DE you use as well as what themes and stuff.

**Comment by ashyon** [comment]
I use GNOME 3 with Adapta Nokto as my theme, for instance. It would look entirely different using Adwaita as the theme.

**Comment by dorkbox** [comment]
RC1 jars are on my server, and there is significantly better detection/support for all sorts of different of Linux combinations now.

I'm doing some issue cleanup to prep for release, so in the unlikely event there are still issues, please create a new one (or re-open this one).
