### ISSUE TITLE
Requires gnome-shell restart on every launch

### ISSUE THREAD

**Issue by ashyon** [dorkbox/SystemTray#29]
It's pretty self-explanatory. Whenever I launch my app, it kills the shell and requires me to execute 'gnome-shell --replace &' on a separate TTY.

**Comment by dorkbox** [comment]
Thanks only because it's running in debug mode. I'll add comments to indicate this won't happen in a release build.

Also, thanks for all the feedback and testing. Keep it coming!!

**Comment by dorkbox** [comment]
Also, what OS? UbuntuGnome? Fedora?

**Comment by ashyon** [comment]
Ah. Is there a way to disable this behavior for now?

No problem! And I'm running Arch Linux with Gnome 3.

**Comment by dorkbox** [comment]
Ah damn, Arch, one OS I haven't tested on yet. I will add that to my matrix, simply because I know Arch has a huge amount of users.

`GnomeShellExtension.ENABLE_SHELL_RESTART=false`

**Comment by ashyon** [comment]
I set the variable but it's still killing the shell, although it doesn't output the line that says to restart the shell.

**Comment by dorkbox** [comment]
It shouldn't be: 

https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/linux/GnomeShellExtension.java#L229

Unless maybe... It's the `gsettings` causing it?  What is likely happening is that in order for the system tray to work on Gnome3, it has to install an extension -- and in order for Gnome3 to pick up the extension, the shell has to be restarted.  This should only happen once, and for some reason your system can't tell that the shell is installed, so it keeps trying to install it.

**Comment by dorkbox** [comment]
I uploaded a "deps" jar to my server, if you want (and this would be hugely helpful) to run off the source (from github is fine) and see WTF is going on in there, that would save me having to fiddle with Arch.  (running XUbuntu 16.04 right now)

**Comment by dorkbox** [comment]
Whoops. I forgot to upload it. it's there now.

**Comment by ashyon** [comment]
Just fyi the deps jar is missing SWT

**Comment by ashyon** [comment]
```
/usr/lib/jvm/default/bin/java -Didea.launcher.port=7533 -Didea.launcher.bin.path=/usr/share/intellijidea-ce/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/default/lib/ant-javafx.jar:/usr/lib/jvm/default/jre/lib/charsets.jar:/usr/lib/jvm/default/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/default/jre/lib/ext/dnsns.jar:/usr/lib/jvm/default/jre/lib/ext/jaccess.jar:/usr/lib/jvm/default/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/default/jre/lib/ext/localedata.jar:/usr/lib/jvm/default/jre/lib/ext/nashorn.jar:/usr/lib/jvm/default/jre/lib/ext/sunec.jar:/usr/lib/jvm/default/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/default/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/default/jre/lib/ext/zipfs.jar:/usr/lib/jvm/default/jre/lib/jce.jar:/usr/lib/jvm/default/jre/lib/jfxswt.jar:/usr/lib/jvm/default/jre/lib/jsse.jar:/usr/lib/jvm/default/jre/lib/management-agent.jar:/usr/lib/jvm/default/jre/lib/resources.jar:/usr/lib/jvm/default/jre/lib/rt.jar:/home/ash/Projects/IdeaProjects/emojikeyboard-java/build/classes/main:/home/ash/Projects/IdeaProjects/emojikeyboard-java/build/resources/main:/home/ash/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.7/751f548c85fa49f330cecbb1875893f971b33c4e/gson-2.7.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.eclipse.swt/org.eclipse.swt.gtk.linux.x86_64/4.3/2e9dff738c66efa2a31b048ac608e454715cf3eb/org.eclipse.swt.gtk.linux.x86_64-4.3.jar:/home/ash/Projects/IdeaProjects/emojikeyboard-java/libs/SystemTray_v2.20_deps.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-common/6.2.1/8e08c604b610cdb91b898c841e8a8254b0f020dc/lucene-analyzers-common-6.2.1.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.4/5fe28b9518e58819180a43a850fbc0dd24b7c050/commons-lang3-3.4.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-core/6.2.1/a1d9ed9e06072fefa13b070628269ccc0a90d7cc/lucene-core-6.2.1.jar:/home/ash/.gradle/caches/modules-2/files-2.1/commons-collections/commons-collections/3.2.2/8ad72fe39fa8c91eaaf12aadb21e0c3661fe26d5/commons-collections-3.2.2.jar:/usr/share/intellijidea-ce/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain net.ashyon.emojikeyboard.Main
14:30:44.507 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is JavaFX detected? true
14:30:44.512 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is SWT detected? false
14:30:44.512 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is using native menus? true
14:30:44.514 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Forcing GTK2 because JavaFX is GTK2
14:30:44.515 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
14:30:44.515 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - FORCE_GTK2: true
14:30:44.583 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - GTK: gtk-x11-2.0
14:30:44.583 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is the system already running GTK? true
14:30:44.583 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Loading libraries
14:30:44.620 [JavaFX Application Thread] ERROR dorkbox.systemTray.SystemTray - Auto-detected that gnome-shell is running
14:30:44.620 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'gnome' desktop
14:30:44.620 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'null' session type
14:30:44.660 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Installing gnome-shell extension
14:30:44.685 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Checking current version of extension for upgrade
14:30:44.689 [JavaFX Application Thread] ERROR dorkbox.systemTray.SystemTray - Cannot auto-detect gnome-shell version
java.lang.NullPointerException: null
	at dorkbox.util.IO.copyStream(IO.java:81)
	at dorkbox.systemTray.linux.GnomeShellExtension.install(GnomeShellExtension.java:169)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:445)
	at dorkbox.systemTray.SystemTray.getNative(SystemTray.java:707)
	at net.ashyon.emojikeyboard.Main.start(Main.java:63)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
14:30:44.714 [JavaFX Application Thread] ERROR dorkbox.systemTray.SystemTray - Unable to load the system tray native library. Please write an issue and include your OS type and configuration
14:30:44.740 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Checking scaling factor for GTK environment, should start with 'uint32', value: 'uint32 0
'
14:30:44.805 [JavaFX Application Thread] INFO dorkbox.systemTray.SystemTray - Successfully Loaded: _GtkStatusIconNativeTray
```

**Comment by ashyon** [comment]
This only happens running it from source btw, it works fine when using the normal jar.

**Comment by dorkbox** [comment]
Hm, for whatever reason, it's returning null for: `GnomeShellExtension.class.getResourceAsStream("extension.js");`

**Comment by dorkbox** [comment]
the `extension.js` file should be right next to `GnomeShellExtension.java`

**Comment by ashyon** [comment]
It's in there, I just checked.

**Comment by ashyon** [comment]
My project is probably not setup right for your library's source. I keep all my resources in src/main/resources.

**Comment by dorkbox** [comment]
I just pushed a change so that the file will only try to copy over if it's not detected

**Comment by dorkbox** [comment]
so you should be able to run from source (provided it thinks you have the extension installed)

**Comment by ashyon** [comment]
What is the extension for, anyway?

**Comment by dorkbox** [comment]
It's ALSO quite likely that the gnome shell extension directory is in the wrong spot

**Comment by dorkbox** [comment]
it's to move the system tray icon next to the clock. UNLESS... Arch said "f* it, we let them there anyways".

Quick question: what does this return for you: `gsettings get org.gnome.shell enabled-extensions`

**Comment by dorkbox** [comment]
every other encounter I've had with gnome forces "tray icons" into an auto-hidden drawer thing. It's possible Arch doesn't do that....

Just to confirm, it's working for you??

**Comment by dorkbox** [comment]
Also, what is `gnome-shell --version` for you

**Comment by ashyon** [comment]
The extension was installed successfully when I was using the jar on your file server, so it's definitely not the wrong directory. Arch AFAIK does not modify any packages, since it's rolling-release and keeps everything as up-to-date as possible, so I'm running GNOME Shell 3.20.4.

Why would you want your library to act differently from all the other appindicators? This is the default GNOME behavior, so why would you install an extension (and require an actual restart of the shell, just to use an application), when you could just use the default behavior and have everything as the user expects anyway?

**Comment by ashyon** [comment]
If the user wants appindicators in the top panel, they can install the [topicons plus](https://extensions.gnome.org/extension/1031/topicons/) extension to customize the behavior of *all* appindicators

**Comment by dorkbox** [comment]
I don't use gnome3, but from reading the forums, people hate not having icons on the top. I personally like having icons at the top, but I know that's not everyone's preference.

>Why would you want your library to act differently from all the other appindicators? This is the default GNOME behavior...

You make a  compelling argument. I'll add "install to top" as an option, by default off, and let the developer decide.

Still -- it should be trying to restart the shell every time it runs... would you be able to help me figure out what's going on with that? I didn't experience that in my testing on UbuntuGnome or Fedora23.

**Comment by ashyon** [comment]
It seems to be reinstalling the extension every time it runs, which is causing that behavior.

**Comment by dorkbox** [comment]
that means it can't find it in `gsettings get org.gnome.shell enabled-extensions`

**Comment by dorkbox** [comment]
for whatever reason... is it there for you?

**Comment by ashyon** [comment]
Extensions don't need to restart the shell when they are installed, anyways.

**Comment by dorkbox** [comment]
> Extensions don't need to restart the shell when they are installed

alas, they did last time i checked.  If gnome 3.20.4 changed that, I can conditional out the restart.

**Comment by dorkbox** [comment]
`GnomeShellExtension.ENABLE_SHELL_RESTART=false;` should also make it not restart... so there's something else doing that, possible when `gsettings set org.gnome.shell enabled-extensions "['SystemTray@dorkbox']"` is called?

**Comment by dorkbox** [comment]
The logic is that I'm basically appending the extension to the end of existing extension

**Comment by ashyon** [comment]
Honestly, I don't think there should be an extension for gnome shell inside a library to be used in applications. It's up to the user, not you nor i nor anyone else developing an application, to choose where the application indicator should go. It's up to the user and how they want their environment configured.

**Comment by dorkbox** [comment]
> Honestly, I don't think there should be an extension for gnome shell inside a library to be used in applications. It's up to the user, not you nor i nor anyone else developing an application, to choose where the application indicator should go. It's up to the user and how they want their environment configured.

Absolutely makes sense. I'll remove the auto-install.

**Comment by ashyon** [comment]
Thank you. We as developers should try to obey the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and let the system handle things how the user expects.

**Comment by dorkbox** [comment]
First time I've read that -- it totally makes sense, and you're right. It should be up to the user.

**Comment by dorkbox** [comment]
I'll track removing the gnome shell extension in issue #30
