### ISSUE TITLE
Not working on OpenSuse 13.2

### ISSUE THREAD

**Issue by jigarzon** [dorkbox/SystemTray#3]
Hi, i'm using opensuse 13.2 but i'm not seeing any icon on my App indicator bar.

Thanks!!

**Comment by dorkbox** [comment]
Are you using the default WM?

**Comment by dorkbox** [comment]
Rather, I should say -- which WM are you using? It seems that there are more than one to choose from. Alternatively -- if you could tell me which install you're using... 

http://download.opensuse.org/distribution/13.2/iso/

**Comment by jigarzon** [comment]
Hi, 

I'm using gnome  3.14.0. Default OpenSuse distro. I'm not seeing any exceptions. This is relevant code:

    File file = new File("/home/....absolute path to: /linux_64/libjna.so");
        System.load(file.getAbsolutePath());
        systemTray = AppIndicatorTray.create("Prueba");

        this.systemTray.createTray("/home/....absolute path to /icono.png");
        this.systemTray.setStatus("Not Running", "icono.png");
        this.systemTray.addMenuEntry("Quit", new SystemTrayMenuAction() {

            @Override
            public void onClick(dorkbox.util.tray.SystemTray st) {
                st.removeTray();
            }
        });

I'm including these 4 dependencies:
   <dependency>
            <groupId>dorkbox</groupId>
            <artifactId>systemtray</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>dorkbox</groupId>
            <artifactId>systemtray-util</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>dorkbox</groupId>
            <artifactId>systemtray-jna</artifactId>
            <version>4.1.0</version>
        </dependency>
        <dependency>
            <groupId>dorkbox</groupId>
            <artifactId>systemtray-jna-platform</artifactId>
            <version>4.1.0</version>
        </dependency>

(I've added your dist and lib to my local maven project.... sorry for the format, github is not recognizing the xml)

**Comment by dorkbox** [comment]
ah. It doesn't look like you are loading the JNA library. System.load(libPath) should do the trick.   You can also try the latest from: https://github.com/java-native-access/jna

**Comment by jigarzon** [comment]
Isn't the 2nd line of my code doing that?

    File file = new File("/home/....absolute path to: /linux_64/libjna.so");
    System.load(file.getAbsolutePath());

**Comment by dorkbox** [comment]
yes, you're correct.

**Comment by dorkbox** [comment]
I'm installing into a VM right now, so I'll figure out what's going on. With all the different disto's, some things get wonky. I try to setup a fallback system -- but it looks like that isn't happening.

**Comment by jigarzon** [comment]
Thanks a lot!

2015-10-21 15:45 GMT-03:00 dorkbox <notifications@github.com>:

**Comment by dorkbox** [comment]
I expect to have something Monday. OpenSuse and gnome are different enough that it's having trouble loading some of the libraries through JNA. The InputConsole project also has this problem on OpenSuse. An interesting problem for sure, and thanks for reporting it!

**Comment by dorkbox** [comment]
Fixed !!  You might notice that part of the fix involves a javascript gnome-shell extension (just to get GTK status icons to display). Because of this lame requirement by gnome-shell, it has to be restarted in order to register the extension. I automatically take care of all this (it is completely transparent to the user), however I added some controls so that this behavior can be tweaked, if wanted.

Here is the extension: https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/util/tray/linux/extension.js

Please re-open if you continue to have problems.
