### ISSUE TITLE
XFCE Icon disappears after two seconds

### ISSUE THREAD

**Issue by FlashTek** [dorkbox/SystemTray#32]
Hello,
when I setup the `SystemTray` like this

    SystemTray.DEBUG = true;
    SystemTray.COMPATIBILITY_MODE=true;
    SystemTray.FORCE_GTK2 = false;
    SystemTray.FORCE_LINUX_TYPE = 1;
    SystemTray tray = SystemTray.getSystemTray();
    URL urk = this.getClass().getResource("/com.flashtek.name/icon.png");
    tray.setIcon(urk);
    //adding menu items

the icon appears in the taskbar on my XFCE Desktop, but after ~2seconds the icon will always disappear. After setting `SystemTray.FORCE_GTK2 = true;` this problem is vanished. But sadly this is no option because I later need to use the `Dekstop.isDesktopSupported()` method which will then cause the entire program to crash with a `GRK-ERROR` (because the application is now using GTK 3 and 2).

How can I solve this problem or is this a real issue of the library?
Regards,
FlashTek

**Comment by dorkbox** [comment]
Can I as what `Desktop.isDesktopSupported()` is used to detect? Maybe I can do some magic and roll in some native functionality.

Also, may I suggest using the newest 3.0 beta if you haven't already? This might solve some of your problems.  With the 3.0 beta, you shouldn't need to specify anything anymore -- since there's been a lot of additions to the detection logic.

I develop this on Xubuntu 16.04, so XFCE shouldn't have any issues.

**Comment by dorkbox** [comment]
(Also, I apologize for taking so long to get back to you -- I was on a short holiday)

**Comment by FlashTek** [comment]
Okay, I will try the 3.0 Beta and report later.
I noticed that on the latest Ubuntu with the Unity Desktop no tray icons created with this library are visible at all. Is this a bug of the lib or some trouble with my system?

**Comment by dorkbox** [comment]
sadly, it is a problem with 2.20.  3.0 beta should fix it.   Note: There are some API changes (hopefully for the better).

**Comment by FlashTek** [comment]
The current source code here on GitHub is not working, in Windows 10 as well as on Ubuntu 16.04 Unity. The `TestTray` is always crashing with this error:

    Exception in thread "main" java.lang.NullPointerException
     	    at dorkbox.systemTray.util.ImageUtils.resizeAndCache(ImageUtils.java:315)
     	    at dorkbox.systemTray.SystemTray.setIcon(SystemTray.java:785)
     	    at dorkbox.TestTray.<init>(TestTray.java:53)
	        at dorkbox.TestTray.main(TestTray.java:39)

**Comment by dorkbox** [comment]
hm, something not quite right. 

can you try with just the provided beta jars from here: https://files2.dorkbox.com

**Comment by FlashTek** [comment]
Hm, do I need to take care of anything special comiling the source code?
The compiled `.jar` seems to be working, but of course I was not able to test, whether the usage of the `Desktop` class is causing a crash of the application (as the code has already been compiled by you). Therefore I would like to modify the `Sample`-code, but this is causing some problems...

**Comment by dorkbox** [comment]
Make a new project with [this jar](https://files2.dorkbox.com/Testing/SystemTray_v2.20_deps.jar) as your only library. Then, copy/paste the sample code + icon resources and you should be able to do what you like.

**Comment by dorkbox** [comment]
If you're still having problems, please open a new issue.
