### ISSUE TITLE
GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

### ISSUE THREAD

**Issue by lodici** [dorkbox/SystemTray#33]
The following code crashes but also hangs, ignoring the try..catch.
```
package test.dorkbox.systray;

import dorkbox.systemTray.SystemTray;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JSlider;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

@SuppressWarnings("serial")
public class TestFrame extends JFrame {

    public TestFrame() {

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(new Dimension(200, 100));
        setLocationRelativeTo(null);
        setTitle("Test");
        setAlwaysOnTop(true);
        setResizable(false);

        JSlider slider = new JSlider(0, 100, 50);
        add(slider);

        try {
            SystemTray.getSystemTray();
        } catch (Exception ex) {
            System.err.println(ex);
        }
    }

    private static void setLookAndFeel(final String laf) {
        try {
            for (final LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if (laf.equals(info.getClassName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.err.println(ex);
        }
    }

    private static void setNativeLookAndFeel() {
        setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    }

    public static void main(String args[]) {
        setNativeLookAndFeel();
        System.out.println("LAF = " + UIManager.getLookAndFeel());
        java.awt.EventQueue.invokeLater(() -> {
            new TestFrame().setVisible(true);
        });
    }

}
```
Running this in Netbeans on Linux Mint 17.3 generates the error -
```
[AWT-EventQueue-0] ERROR dorkbox.systemTray.SystemTray - Unable to load the system tray native library. Please write an issue and include your OS type and configuration

(java:16435): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(java:16435): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(java:16435): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```
I then have to manually stop the process from the IDE.

If I comment out the call to ``setNativeLookAndFeel()`` then ``SystemTray.getSystemTray();`` works but I get the default look and feel -
![screenshot from 2016-11-30 10 51 14](https://cloud.githubusercontent.com/assets/2443519/20749959/704e6fc8-b6ec-11e6-8f4f-489eaffe3779.png)

If I comment out ``SystemTray.getSystemTray();`` instead then  ``setNativeLookAndFeel()`` works and the dialog looks like -
![screenshot from 2016-11-30 10 50 41](https://cloud.githubusercontent.com/assets/2443519/20750019/ab2ce08e-b6ec-11e6-814e-5ec70c61af61.png)

I tried adding the ``SystemTray.COMPATIBILITY_MODE=true`` and ``System.setProperty("SWT_GTK3", "0")`` but these made no difference.

Even if there is no solution I think it should at least honour the try..catch wrapper so that it can fail gracefully.

Specs
```
SystemTray-2.20.jar
SystemTray-Dorkbox-Util-2.20.jar
jna-4.2.2.jar
java version "1.8.0_111"
Netbeans 8.1
Linux Mint 17.3
```

**Comment by dorkbox** [comment]
Sorry for getting back so late... I've been swamped with work.

Can you try using the beta 3.0 jar from here: #22? I've done a lot of work compatibility-wise for 3.0, and it might already solve your problem.

**Comment by dorkbox** [comment]
Also, as a note, i'll add setting/changing the native L&F in the test examples, since that I what I use for my main project as well, and it is important for everything to work with a different L&F.

**Comment by dorkbox** [comment]
RC1 jars are on my server, and there is significantly better detection/support for all sorts of different of Linux combinations now. I specifically verified that your set LAF use-case correctly works (this was on XUbuntu 16.04 and switching between Metal LAF and Nimbus LAF).

I'm doing some issue cleanup to prep for release, so in the unlikely event there are still issues, please create a new one (or re-open this one).
