### ISSUE TITLE
GitHub and Maven Version identical?

### ISSUE THREAD

**Issue by ultrasites** [dorkbox/SystemTray#37]
Hello,

are the current GitHub Version and Maven Version identical?

The Maven Version 2.20 has no `getNative()` or `get()` Method. Only `getSystemTray()`.

Can you help me?

**Comment by dorkbox** [comment]
It's currently preparing for release, and once it's released the version will be identical everywhere. 

 I would recommend downloading the Release Candidate from issue #22.
