### ISSUE TITLE
UI manager support ( LINUX )

### ISSUE THREAD

**Issue by aurbanoDev** [dorkbox/SystemTray#38]
I cant make it work using look and feel customization. 
is it supports UI manager ? 

UIManager.setLookAndFeel() seams to be my problem.
I tried to set SWT_GTK var and use the tips of the wiki with no success so far. 

Cheers.

Tracing the errors:
(java:8658): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(java:8658): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(java:8658): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

**Comment by dorkbox** [comment]
which version are you using?

**Comment by aurbanoDev** [comment]
v2.20

**Comment by dorkbox** [comment]
This problem should be resolved in the upcoming release. 

Please use the release candidate available in issue #22 or wait for the 3.0 release.
