### ISSUE TITLE
No transparency with openjdk

### ISSUE THREAD

**Issue by raginggoblin** [dorkbox/SystemTray#4]
The icon looks perfect using Oracle JDK. But my users want to use OpenJDK. The icon than displayed has no transparency, just like the default Swing systray icon.

Environment: Ubuntu 15.10 with Unity 7 and GGleb/indicator-systemtray-unity, OpenJDK 8

**Comment by dorkbox** [comment]
interesting. I'm on Ubuntu 15.10 (but with oracle). i'll check it out

**Comment by dorkbox** [comment]
Also, I recently did a ton of updates -- which version of SystemTray are you using?

**Comment by dorkbox** [comment]
Works on this end: 
Execution JVM: Oracle Corporation  OpenJDK 64-Bit Server VM 1.8.0_66-internal


Can you share how you're creating the systemtray? Are you loading JNA?

**Comment by raginggoblin** [comment]
I did an update to the last code. Somehow it works now. Don't know what went wrong. Sorry to bother you. Thanks for the library, good work. It would be great if this one is at maven central.
