### ISSUE TITLE
Inconsistent Icon Sizes

### ISSUE THREAD

**Issue by tresf** [dorkbox/SystemTray#41]
If this is a technical limitation, please feel free to close as wont-fix, but I wanted to provide some visual feedback for Ubuntu 12.04, 14.04, 16.04.

* 12.04 seems small.
* 14.04 seems just right.
* 16.04 seems cutoff.

**Ubuntu 12.04**
> ![image](https://cloud.githubusercontent.com/assets/6345473/22052848/e61df94a-dd1a-11e6-9238-f9793c0793fb.png)

**Ubuntu 14.04:**

> ![image](https://cloud.githubusercontent.com/assets/6345473/22052709/bd78b58a-dd19-11e6-990d-ac2c101eefe6.png)

**Ubuntu 16.04:**

> ![image](https://cloud.githubusercontent.com/assets/6345473/22052063/b7082d1a-dd15-11e6-9229-fed8f53d0816.png)

**Comment by dorkbox** [comment]
Fixed in bf5142919d4bab1d675d64a1b137d071ba1188a7
