### ISSUE TITLE
Windows scaling for menu entries is the wrong size

### ISSUE THREAD

**Issue by dorkbox** [dorkbox/SystemTray#43]
The menu entry scaling for windows is either too small, or too large - depending on the DPI settings of the PC. Critical for releasing #22

**Comment by Vzor-** [comment]
Example on Window 10 1080P with 125% scaling 

![capture](https://cloud.githubusercontent.com/assets/10621658/22310790/6010f596-e31e-11e6-9bd2-57bf1355d4d1.PNG)

**Comment by Vzor-** [comment]
Intended behavior window 10 720p, no scaling
![capture](https://cloud.githubusercontent.com/assets/10621658/22311915/ad1f3d02-e323-11e6-8765-1aef2499c7fc.PNG)

**Comment by dorkbox** [comment]
fixed.

**Comment by Vzor-** [comment]
Looks great now (ran on the original system) 
![capturefix](https://cloud.githubusercontent.com/assets/10621658/22344507/77bf6450-e3ca-11e6-8a54-fd5952d0a362.PNG)

**Comment by tresf** [comment]
FYI, it's conventional to cross-reference the commit(s) or PRs used when closing a bug report.

That said, this was closed via https://github.com/dorkbox/SystemTray/compare/03e56ad...9abc2bd
