### ISSUE TITLE
Windows cannot use the 'AutoDetect' SystemTray type, defaulting to Swing

### ISSUE THREAD

**Issue by tresf** [dorkbox/SystemTray#48]
Is there a recommended approach as to not receive benign warnings in our logs?  We're just using "plain old" `SystemTray.get();`, I wouldn't expect warnings if this is the default usage.

Although warnings seem minor, for projects which rely on users submitting logs for support purposes, they only expect to see warnings that they've created or are valid as to the performance of the software.

**Comment by dorkbox** [comment]
You are absolutely correct, and those messages shouldn't have been there. The only message that should show is that the system tray loaded.

Fixed with commit: fe6b09e8dd6b3b4bd8c53e1aebf4b491a2917784
