### ISSUE TITLE
Menu separator missing macOS

### ISSUE THREAD

**Issue by tresf** [dorkbox/SystemTray#49]
Using `SystemTray.get().getMenu().add(new Separator());`, it doesn't seem to appear on macOS.

This logic works fine using a standard awt menu.

![image](https://cloud.githubusercontent.com/assets/6345473/23198614/d2eec3e4-f896-11e6-86fa-d6ab31053dc5.png)

**Comment by dorkbox** [comment]
It turns out checkbox was missing as well. I don't know how we missed this while testing.

Fixed with commit: 7e89c7b5831a546d82c2456c11f02436bbd0f979
