### ISSUE TITLE
Getting error when I right click the tray icon

### ISSUE THREAD

**Issue by tgharib** [dorkbox/SystemTray#5]
I'm running KDE Plasma 5.4 on Manjaro Linux 64-bit.

So I used the example in your README.md and I can see the tray icon but I can't right click. When I right click, I get the following error:

`(java:27561): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.`

Here's a link to the repo if needed: https://github.com/tgharib/PrayerApp

The relevant line of code: https://github.com/tgharib/PrayerApp/blob/master/src/main/java/com/github/tgharib/PrayerFrame.java#L98

**Comment by dorkbox** [comment]
Are you loading JNA?

**Comment by dorkbox** [comment]
I didn't see it getting loaded -- unless, if you are using the official JNA from maven, this isn't necessary.

**Comment by tgharib** [comment]
Yes, I should be. I have `compile 'net.java.dev.jna:platform:3.5.2'` under dependencies in build.gradle.

Here is what happens when I remove the JNA dependency:

[main] ERROR dorkbox.util.tray.SystemTray - Unsupported tray type!
Exception in thread "main" java.lang.NullPointerException
	at com.github.tgharib.PrayerFrame.<init>(PrayerFrame.java:99)
	at com.github.tgharib.Program.<init>(Program.java:27)
	at com.github.tgharib.Program.main(Program.java:53)

**Comment by dorkbox** [comment]
Hm. Strange that it's not adding submenus/working correctly. I'll spin-up a manjaro linux KDE vm, and see what's going on.

**Comment by tgharib** [comment]
Here's a video of the symptom if it's worth anything: https://d.maxfile.ro/ltcuicdzow.mp4

**Comment by tgharib** [comment]
I tried it in a Ubuntu VM and it worked after installing the libappindicator-dev package.

**Comment by tgharib** [comment]
As a non-important side-note, it seems that the tooltip doesn't work under Ubuntu.

`SystemTray.create("Test");` should create a tray icon with a tooltip text of "Test", right?

**Comment by dorkbox** [comment]
You're correct. I had a HDD failure, which is why i disappeared for a few days.


on a fresh install, i noticed the same things you did, so I'll fix that as well.

**Comment by tgharib** [comment]
No problem, take your time

**Comment by dorkbox** [comment]
@tgharib  Alright, i've got some major updates in. One issue, regarding tooltips and 'right-click', is that I have to cater to the lowest-common-denominator (which is application indicators), which do not support tooltips or right-click.

Can you see if things are working for you? I'm unable to create VMs at the moment to test.

**Comment by tgharib** [comment]
I've updated my libs in [my project](https://github.com/tgharib/PrayerApp) and updated the calls to match the new API. The bad news is that while previously I could see the system tray icon but I couldn't right click, now I can't even see the system tray icon so I can't test the right click functionality. The good news is that it still works great under Ubuntu.

**Comment by dorkbox** [comment]
Right-click won't ever work (a limitation put into place), but left click will. Since the auto-dection stuff clearly isn't working correctly, i'll spin back up a manjaro vm when I can.

**Comment by tgharib** [comment]
@dorkbox Oh right click is never supposed to work intentionally? It seems I can left click and right click in my Ubuntu VM - not sure if that's a bug.

**Comment by dorkbox** [comment]
in some implementations, leftclick and right click will open the same menu (app indicators, ie: ubuntu), and for everything else, left/right could open separate menus (they now open the same menu)

**Comment by dorkbox** [comment]
The issue was that appindicators won't let me have separate menus for left/right click

**Comment by tgharib** [comment]
Oh I see. That's actually a good thing that appindicators disable separate menus for left/right click because from an end-user perspective, that would be extremely confusing if there were two different menus. I don't think I've ever encountered a system tray icon that had separate menus on both Windows and Linux.

**Comment by dorkbox** [comment]
but, left and right click should BOTH work - it's just the same menu.

**Comment by dorkbox** [comment]
Finally figured out what's going on with Manjaro. I should have a fix in the next few days -- turns out they're using a bugged version of libappindicator.

**Comment by dorkbox** [comment]
Alright, this should be working now. One of the things I added support for, is having icons in the menu as well.

I'm going to close this issue, and if you're still having problems let me know. Note that I added two issues (and locked them), because when running under an Arch distro (it uses an old, buggy version of libappindicator), you'll see some warnings in the console. These are expected, and can only be fixed when the arch community decides to pull in changes to appindicator that were made back in 2013...

**Comment by dorkbox** [comment]
Also, of note: I'm working on getting maven releases out, which should simplify things a lot on your end.

**Comment by tgharib** [comment]
Awesome, maven releases will make building easier. :thumbsup:

I'll test your changes out as soon as I get the chance. Surprised that Arch has packages from 2013; I always assumed all their packages are bleeding age.

**Comment by dorkbox** [comment]
I assumed the same thing and it blew my mind when I read the date on the bug reports/fixes. There are newer/different versions of libappindicator, they just aren't in by default.

**Comment by tgharib** [comment]
Updated the libs and did a bit of clean-up on my side. It works excellently and I pushed a release :)

**Comment by dorkbox** [comment]
awesome! Glad it's now working.

**Comment by dorkbox** [comment]
bleh. I hate maven, and no clear place to find their REST api.  (as I use my own build system).

Anyways, this SHOULD do the trick. Should I have it just be a single POM? (I'm uncertain if I should, as I don't want a hard dependency, via maven, on the utilities library, which at some point, I will release in full...)

<dependency>
  <groupId>com.dorkbox</groupId>
  <artifactId>SystemTray</artifactId>
  <version>1.8</version>
</dependency>

<dependency>
  <groupId>com.dorkbox</groupId>
  <artifactId>SystemTray-Dorkbox-Util</artifactId>
  <version>1.8</version>
</dependency>

**Comment by dorkbox** [comment]
edited to fix formatting.

**Comment by tgharib** [comment]
Awesome, I swapped out the JARs in my repo and replaced it with your maven project and it compiled and ran as it should. I agree that it should be two separate POMs if the utilities library is going to be released independently. However, I would add `SystemTray-Dorkbox-Util` to the dependencies of `SystemTray` so that way, your users only have to add the `SystemTray` library in their dependency manager.

Unfortunately, it seems that transitive dependencies don't work so I created this [SO post](http://stackoverflow.com/questions/34227936/gradle-transitive-dependencies-not-working). It seems that gradle pulls SystemTray's dependency on JNA but the program doesn't see the JNA on runtime. I think it might be because SystemTray's dependency on `net.java.dev.jna:jna` is listed as compile scope instead of runtime scope. Could you try changing it to runtime scope? I'm not a dependency management expert though so I'm not sure if that will fix it.

**Comment by dorkbox** [comment]
Sure, I'll combine the two, and when I  release the utils - I'll add a new "release"/POM that has a different dependency with the full utils instead of the small one. 

I'll also research the runtime scope thing.... I had read that compile scope includes runtime, so bleh. I'm no expert either and maven can be really weird w/ some things.

**Comment by tgharib** [comment]
>Sure, I'll combine the two, and when I release the utils - I'll add a new "release"/POM that has a different dependency with the full utils instead of the small one.

Oh sorry if I pressured you into combining them into one POM because that's not what I intended (I think they should remain separate like you said). What I meant by adding `SystemTray-Dorkbox-Util` to the dependencies of `SystemTray` is just adding:

<dependency>
<groupId>com.dorkbox</groupId>
<artifactId>SystemTray-Dorkbox-Util</artifactId>
<version>1.9</version>
<scope>compile</scope>
<type>pom</type>
</dependency>

to the [POM file of SystemTray](http://central.maven.org/maven2/com/dorkbox/SystemTray/1.9/SystemTray-1.9.pom) under <dependencies>.

**Comment by dorkbox** [comment]
ah, yes -- that's what I meant too. We're on the same page :)

**Comment by dorkbox** [comment]
Uploaded version v1.10 (might take a few hours to sync with maven central) -- now with several changes... hopefully it works without problems now :)

```
<dependency>
  <groupId>com.dorkbox</groupId>
  <artifactId>SystemTray</artifactId>
  <version>1.10</version>
</dependency>
```

**Comment by tgharib** [comment]
[owner@Taha-PC PrayerApp]$ gradle run
    :compileJava
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Could not resolve all dependencies for configuration ':compile'.
    > Could not find com.dorkbox:SystemTray-Dorkbox-Util:v1.10.
      Searched in the following locations:
          https://repo1.maven.org/maven2/com/dorkbox/SystemTray-Dorkbox-Util/v1.10/SystemTray-Dorkbox-Util-v1.10.pom
          https://repo1.maven.org/maven2/com/dorkbox/SystemTray-Dorkbox-Util/v1.10/SystemTray-Dorkbox-Util-v1.10.jar
      Required by:
          :PrayerApp:unspecified > com.dorkbox:SystemTray:1.10
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    
    BUILD FAILED
    
    Total time: 3.736 secs

It appears there's a small typo where the v in `v1.10` in the version tag needs to be removed:

    <dependency>
    <groupId>com.dorkbox</groupId>
    <artifactId>SystemTray-Dorkbox-Util</artifactId>
    <version>v1.10</version>
    <scope>COMPILE</scope>
    </dependency>

**Comment by dorkbox** [comment]
oh whoops! You're right. I missed that entirely.  I've pushed up version 1.11

**Comment by tgharib** [comment]
I'm currently in the middle of exams. I'll give it a run in 2-3 days. :)

**Comment by tgharib** [comment]
I just tried it today and it seems to be working. It pulls the SystemTray-Dorkbox-Util dependency automatically. It seems that all the other transitive dependencies are working too. I'm curious: did you do something to get the other transitive dependencies working or did it just decide to work by itself?

**Comment by dorkbox** [comment]
It was a PITA. I had to muck with the main POM a little (guessing/hoping it was the right change) and I changed the transitive dependencies to "runtime". It's like there is a ton of documentation, but NOTHING on how to actually use it (or a simple, straightforward example).
