### ISSUE TITLE
Implement tooltips for Swing

### ISSUE THREAD

**Issue by tresf** [dorkbox/SystemTray#50]
Although the tray icon supports the tooltip since https://github.com/dorkbox/SystemTray/commit/ec9499c1bbbfc31a5aa91c1455fad666eec732fe, the `JMenuItem`'s still do not.

Why use tooltips for menus?  Well, Microsoft uses it for some ribbon menu items, such as "Open command prompt" item.  Google Drive uses it for displaying full paths for files.

The decision may be made to not support them at all and that is fine, but it may be considered a regression on Windows for those coming from `JXTrayIcon` and friends.

**Comment by dorkbox** [comment]
I'll add support for tooltips, but not for 3.2 release (since that is almost ready to go out the door). I think it's OK to have tooltips in swing, because I fixed the Swing tray icon transparency issue for Linux - so Swing trays now behave nicely on all OSes.

**Comment by dorkbox** [comment]
Added via commit 65e7c669b5f6cf592246af46fa204089e193ea30 and 64bd95d86171c9c84a85ef1d6c74958a47bcff95. 

Of note: tooltips are supported by Swing and GtkStatusIcons. AWT and AppIndicator menus do not support tooltips -- as such, there is a 1-time warning emitted so developers are aware they are using a feature that is not consistent across all platforms.

**Comment by dorkbox** [comment]
check out the pre-release [here](https://github.com/dorkbox/SystemTray/releases/tag/3.2_beta2)
