### ISSUE TITLE
How to add mouse click listener to the systemtray

### ISSUE THREAD

**Issue by kiraniyengar** [dorkbox/SystemTray#53]
Need double click listener on the system tray so that we need to open the application. We want it similar to outlook

**Comment by dorkbox** [comment]
Sorry, but this is not possible, as that feature is only available for Windows, and this library focuses on cross platform features only.

**Comment by Sebastian-0** [comment]
Sorry for replying to an old issue but this must be possible to do for at least some platforms since it works for AWT in both windows and linux (at least the distros I've tested).
