### ISSUE TITLE
No tray icons on Ubuntu GNOME 17.04

### ISSUE THREAD

**Issue by stefan-reich** [dorkbox/SystemTray#56]
Not really a SystemTray issue - maybe -, but just Ubuntu's arrogance I guess. Details [here](https://www.youtube.com/watch?v=ljj2c2Ie9NU).

**Comment by dorkbox** [comment]
It might be a SystemTray issue -- Ubuntu Gnome does things a lot differently than a proper Gnome DE. I tested on Ubuntu Gnome 16.04 -- I'll see what's going on with 17.04.

If you log out, then log back in -- does it work correctly? There is a GnomeShell extension that is installed (and the shell is supposed to automatically restart), and it looks like Ubuntu Gnome 17.04 might have removed support for it.

**Comment by dorkbox** [comment]
fixed in c9f6b3f044f8416ceb168e588dd963aa1b119291
