### ISSUE TITLE
Gdk-CRITICAL - issue #19 on gnome 3.24.2

### ISSUE THREAD

**Issue by ladislavlencucha** [dorkbox/SystemTray#57]
Hi,

it seems issue #19 is back:
https://github.com/dorkbox/SystemTray/issues/19

I have com.dorkbox/SystemTray 3.1 and it occurs on my ubuntu 17.04 with gnome shell 3.24.2.

**Comment by dorkbox** [comment]
Thanks for reporting it. I'll look into it before the final 3.2 release.

**Comment by ladislavlencucha** [comment]
Thanks. I've done multiple tests and it seems the error does not always happen. It has something to do with other applications running on my machine, which is strange. In my case it helped to stop ghetto-skype (electron framework) and Squirrel SQL Client (java).

**Comment by dorkbox** [comment]
can you try the 3.2 beta and see what happens? It's under releases. It's an "all in one" jar, so if you want to drop it in your project as a replacement, edit the jar to delete everything not in the dorkbox directory, then save the changes.

**Comment by dorkbox** [comment]
Hm. I'm not able to reproduce this issue -- please re-open if there are still problems, and we can try to track down what is going on.
