### ISSUE TITLE
macOS - Menu text stops to works after upgrade from 3.1 -> 3.3

### ISSUE THREAD

**Issue by dyorgio** [dorkbox/SystemTray#58]
Hi @dorkbox!

When I upgrade lib version to 3.3 from 3.1 my Menu stops to shows the label.

I debugged and found the problem 👍  dorkbox.systemTray.ui.awt.AwtMenu.

It is using ```_native.setLabel()``` for menu text and tooltip.

Current workaround is setting tooltip as same text as label.

I believe that AWT doesn't support tooltips for Menus.

**Comment by dorkbox** [comment]
Thanks for reporting. I'll fix it this weekend.

**Comment by dorkbox** [comment]
fixed.
