### ISSUE TITLE
Debug info enabled in 3.3 on maven.

### ISSUE THREAD

**Issue by dyorgio** [dorkbox/SystemTray#59]
Debug flags appears to be turned on in maven repository (version 3.3):

```
09:38:36.596 [main] DEBUG dorkbox.systemTray.SystemTray - Tray indicator image size: 44
09:38:36.600 [main] DEBUG dorkbox.systemTray.SystemTray - Tray menu image size: 32
```

**Comment by dorkbox** [comment]
It's off. 

If you open the jar file, specifically ````SystemTray.class````, you'll see ````public static boolean DEBUG;````  Since it's non-final, you might have it turned on somewhere else.

Of note, in 3.2 I had forgotten to turn it off.

**Comment by dyorgio** [comment]
You are right!
I think that the problem is on theses lines:

```java
logger.debug("Tray indicator image size: {}", Integer.valueOf(trayImageSize));
logger.debug("Tray menu image size: {}", Integer.valueOf(menuImageSize));
```

I have no configuration for sf4j...

Maybe use DEBUG flag, like another parts of code:

```java
if (DEBUG) {
    logger.debug("Tray indicator image size: {}", Integer.valueOf(trayImageSize));
    logger.debug("Tray menu image size: {}", Integer.valueOf(menuImageSize));
}
```

**Comment by dorkbox** [comment]
ah! yes, I'll switch those to the debug -- i missed them. Thank you for finding it!

**Comment by dorkbox** [comment]
fixed.
