### ISSUE TITLE
Tray menu cleaning is not working on Mac OS (awt)

### ISSUE THREAD

**Issue by CORRUPTOR2037** [dorkbox/SystemTray#60]
Menu cleaning is not working on Mac OS. Menu items container removes all elements, but despite this all removed elements stays in tray menu. 

Example:
`SystemTray systemTray = SystemTray.get();`
`Menu mainMenu = systemTray.getMenu();`
`MenuItemAction menuItemAction1 = new MenuItemAction() { ... };`
`mainMenu.add(new MenuItem("item 1", menuItemAction1));`
`...`
`mainMenu.clear();`
`MenuItemAction menuItemAction2 = new MenuItemAction() { ... };`
`mainMenu.add(new MenuItem("item 2", menuItemAction2));`

Result for Mac OS:
- item 1
- item 2

Result for Linux/Windows
- item 2

Debug log for Mac OS:
OS: Mac OS X
Arch: x86_64
Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_131
Is AutoTraySize? true
Is JavaFX detected? true
Is SWT detected? false
Forced tray type: AutoDetect
FORCE_GTK2: false
Successfully changed mouse trigger for MacOSX
ScalingFactor is '2.0', tray icon size is '32'.
ScalingFactor is '0.0', tray menu size is '16'.
Successfully loaded type: _AwtTray

**Comment by dorkbox** [comment]
So this is not a problem?

**Comment by CORRUPTOR2037** [comment]
Yes, sorry. Problem was that I tried to clean menu without checking is it currently in event dispatch thread. It is non-OS problem and is easily fixing.
