### ISSUE TITLE
GTK MenuItem doesn't work if added before Menu is added. 

### ISSUE THREAD

**Issue by dyorgio** [dorkbox/SystemTray#62]
If you include a Menu with children (MenuItem) you MUST add the Menu to systray BEFORE add a child (MenuItem) to this menu.

Otherwise entire menu is not included and this critical/warning is printed on console:

```
(java:87583): Gtk-CRITICAL **: gtk_container_remove: assertion '_gtk_widget_get_parent (widget) == 
GTK_WIDGET (container) || GTK_IS_ASSISTANT (container) || GTK_IS_ACTION_BAR (container) || 
GTK_IS_POPOVER_MENU (container)' failed

(java:87583): Gtk-WARNING **: Can't set a parent on widget which has a parent
```

No errors on program execution.

**Comment by dorkbox** [comment]
Ah. Thanks for the info. This should be fixed pretty soon.

**Comment by dorkbox** [comment]
Fixed.
