### ISSUE TITLE
QUESTION: make lib works when run program as another user.

### ISSUE THREAD

**Issue by dyorgio** [dorkbox/SystemTray#63]
I'm trying to start my program with root to another users on machine.

I already tried "runuser"(-l and -u) and "su username", but no way to make it works.

The best try, for now was:
```bash
sudo runuser -l username -c "DISPLAY=:0 XDG_CURRENT_DESKTOP=$XDG_CURRENT_DESKTOP program-name"
```

The program works, without error, but no icon appears :(, somebody have any glue who to make it works?

**Comment by dyorgio** [comment]
Almost done with:

```bash
sudo su username /bin/sh -c "XDG_CURRENT_DESKTOP=$XDG_CURRENT_DESKTOP program-name"
```

But this warning appears:
```
18:29:30.061 [main] WARN dorkbox.systemTray.SystemTray - Attempting to load the SystemTray as the 'root/sudo' user. This will likely not work because of dbus restrictions. Using the Swing Tray type instead.
```

But process is running as my user:
<img width="547" alt="captura de tela 2017-09-17 as 18 30 31" src="https://user-images.githubusercontent.com/1438251/30525107-5e7f6994-9bd6-11e7-907f-2282e24f6db8.png">

**Comment by dorkbox** [comment]
What OS and window manager?

In most cases, because of the way dbus works, the application running must also be the same user that the desktop is running under. There are ways around it, but involve managing the dbus directly, which is far to much effort for me.

See if you can get it to work without using ````sudo```` at all, since the check for running as root is via ````System.getenv("SUDO_USER")````.

Since it's super easy to add a "root override", where all root checks are disabled I'll do that real quick. If it works, it works, if not - there's nothing I know of to make it work.

**Comment by dyorgio** [comment]
I'm testing in Ubuntu 16.04 with Unity.

Sadly it doesn't work with:
```java
dorkbox.systemTray.SystemTray.AUTO_FIX_INCONSISTENCIES = false;
```
I tried only with su, but before I need to enter in a bash with sudo (same think at the end).
:(.

My application needs a "service" that start my program on users sessions if it is not open (crashed or terminated by user), like a auto-restart (keep alive).

Can you give me some advices about manage bus directly?

**Comment by dorkbox** [comment]
(this specifically has to do with app-indicators. I just pushed version 3.7, which has ````SystemTray.ENABLE_ROOT_CHECK````

**Comment by dorkbox** [comment]
I have no idea how to manage the dbus directly. My research ended when I discovered that it is not easy. However, I've tested against Ubuntu 16.04 + Unity, and the fallback "Swing" tray type worked in a VM.

**Comment by dyorgio** [comment]
Yes, I can confirm that swing is working here too :).

**Comment by dorkbox** [comment]
Ah, good to know swing works in more than a VM. Can you try 3.7 and tell me if ````SystemTray.ENABLE_ROOT_CHECK=false```` works in your situation? All it does is disable the warning + swing fallback (since ````SystemTray.AUTO_FIX_INCONSISTENCIES```` does a lot of things, it's best to leave that ````true````)

**Comment by dorkbox** [comment]
As far as DBUS stuff goes, If you can get a C example running (I have some test examples in the test directory), I can probably port that to java.

**Comment by dyorgio** [comment]
I got it!

Using this command it works (with root warning):
```
sudo su username /bin/sh -c "DBUS_SESSION_BUS_ADDRESS='unix:abstract=/tmp/dbus-cLtEoBPmgC' XDG_CURRENT_DESKTOP=$XDG_CURRENT_DESKTOP program-name"
```

I get "unix:abstract=/tmp/dbus-cLtEoBPmgC" from /run/user/{uid}/dbus-session.

What do you think? it is a good start point to include into lib?

**Comment by dorkbox** [comment]
Awesome! Thanks for figuring it out - i'll definitely include that info.

If you want, you can disable the root warning/checks via ````SystemTray.ENABLE_ROOT_CHECK=false```` now.

**Comment by dyorgio** [comment]
Example to run as user with root:
```java
        // Get dbus-daemon PID
        Process process = Runtime.getRuntime().exec(new String[]{//
            "/bin/sh", "-c", //
            "ps aux | grep \"^" + user + " \" | grep \"dbus-daemon\" | grep \"unix:\" | awk '{print $2}'" //
        });
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        String pid = reader.readLine();
        reader.close();

        // Read DBUS env values
        Map<String, String> dbusEnv = new HashMap();
        process = Runtime.getRuntime().exec(new String[]{//
            "/bin/sh", "-c", //
            "cat /proc/" + pid + "/environ | tr '\\0' '\\n'" //
        });
        
        reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        String line;
        int splitIndex;
        while ((line = reader.readLine()) != null) {
            splitIndex = line.indexOf('=');
            if (splitIndex != -1) {
                dbusEnv.put(line.substring(0, splitIndex), line.substring(splitIndex + 1));
            }
        }
        reader.close();

        String xdgDesktop = dbusEnv.get("XDG_CURRENT_DESKTOP");
        if (xdgDesktop == null) {
            xdgDesktop = "Unity"; // Ubuntu Rules!
        }

        String display = dbusEnv.get("DISPLAY");
        if (display == null) {
            display = ":0"; // display default
        }

        String dbusAddress = dbusEnv.get("DBUS_SESSION_BUS_ADDRESS");

        process = Runtime.getRuntime().exec(new String[]{//
            "runuser", //
            user,//
            "-c",//
            "/bin/sh -c \"DISPLAY=" + display + " DBUS_SESSION_BUS_ADDRESS=" + dbusAddress + " XDG_CURRENT_DESKTOP=" + xdgDesktop + " YOUR-COMMAND""//
        });
```

**Comment by dorkbox** [comment]
Perfect! May I add this as a Utility method under Apache 2.0?

**Comment by dyorgio** [comment]
@dorkbox always :D

**Comment by tresf** [comment]
@dorkbox sorry to go a bit off-topic, but @dyorgio does this script [launch a process as another user with the environment setup properly for Java to theme the application](https://stackoverflow.com/questions/40603418/have-script-detect-gnome-session)?

**Comment by dyorgio** [comment]
@tresf, if GNOME_DESKTOP_SESSION_ID is present in dbus-daemon yes, you just need to include in your version this:
```java
dbusEnv.get("GNOME_DESKTOP_SESSION_ID");
```
In my Ubuntu I don't have this, only theses:
```properties
XDG_SESSION_TYPE=x11
DESKTOP_SESSION=ubuntu
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-cLtEoBPmgC
SESSIONTYPE=gnome-session
XDG_SESSION_ID=c2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_DESKTOP=ubuntu
GDMSESSION=ubuntu
DESKTOP_SESSION=ubuntu
XDG_CURRENT_DESKTOP=Unity
XDG_SESSION_DESKTOP=ubuntu
```

**Comment by tresf** [comment]
@dyorgio thanks.  If you think you can tackle the linked stackoverflow article, we'd be willing to put a bounty on it.

**Comment by dyorgio** [comment]
@tresf Done :), please, tell us if it works or not.

**Comment by tresf** [comment]
@dyorgio thanks!!  Can you email me? `tres.finocchiaro@gmail.com`

**Comment by dyorgio** [comment]
Hi guys,

In last fedora (30) dbus-daemon was replaced (I guess) by dbus-broker-launch, but I can't make it works with SystemTray Lib, no appindicator is showing and if I pass mouse over tray area, process is killed by SIGTRAP signal....

If I run same application as user, everything works... Anybody tried to run an app that uses this lib with root as another user with success on Fedora 30?
