### ISSUE TITLE
KDE - On shutdown in KDE 17.04, libappindicator fails

### ISSUE THREAD

**Issue by apetrelli** [dorkbox/SystemTray#65]
When shutdown is performed, I see some critical errors in the log.
It seems that the reason is that in
_AppIndicatorNativeTray
there is a call to 
AppIndicator.app_indicator_set_menu
with the appIndicator parameter set to null!

Here is the log from the start to the exit
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dorkbox.util.Swt (file:/home/anpetrel/.m2/repository/com/dorkbox/SystemTray/3.11/SystemTray-3.11.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of dorkbox.util.Swt
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
14:02:40.859 [main] DEBUG dorkbox.systemTray.SystemTray - OS: Linux
14:02:40.863 [main] DEBUG dorkbox.systemTray.SystemTray - Arch: amd64
14:02:40.864 [main] DEBUG dorkbox.systemTray.SystemTray - Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 9
14:02:40.864 [main] DEBUG dorkbox.systemTray.SystemTray - Is Auto sizing tray/menu? true
14:02:40.864 [main] DEBUG dorkbox.systemTray.SystemTray - Is JavaFX detected? false
14:02:40.864 [main] DEBUG dorkbox.systemTray.SystemTray - Is SWT detected? false
14:02:40.959 [main] DEBUG dorkbox.systemTray.SystemTray - Java Swing L&F: Metal
14:02:40.959 [main] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
14:02:40.959 [main] DEBUG dorkbox.systemTray.SystemTray - Force GTK2: false
14:02:40.959 [main] DEBUG dorkbox.systemTray.SystemTray - Prefer GTK3: true
14:02:41.019 [main] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'KDE' desktop environment
14:02:41.136 [main] DEBUG dorkbox.util.jna.linux.GtkLoader - GTK: libgtk-3.so.0
14:02:41.137 [GTK Native Event Loop] DEBUG dorkbox.util.jna.linux.GtkEventDispatch - Running GTK Native Event Loop
14:02:41.245 [main] DEBUG dorkbox.systemTray.SystemTray - GTK Version: 3.22.11
14:02:41.246 [main] DEBUG dorkbox.systemTray.SystemTray - Is the system already running GTK? false
14:02:41.282 [main] DEBUG dorkbox.util.jna.linux.AppIndicator - Loading library (first attempt): 'libappindicator3.so.1.0.0'
14:02:41.407 [main] DEBUG dorkbox.systemTray.SystemTray - Tray indicator image size: 22
14:02:41.407 [main] DEBUG dorkbox.systemTray.SystemTray - Tray menu image size: 16
14:02:41.522 [main] INFO dorkbox.systemTray.SystemTray - Successfully loaded type: _AppIndicatorNativeTray
14:02:41.523 [main] WARN dorkbox.systemTray.SystemTray - Tooltips are not consistent across all platforms and tray types.
14:02:41.643 [GTK Native Event Loop] INFO dorkbox.systemTray.SystemTray - Using Fake CheckMark: true
14:02:41.644 [GTK Native Event Loop] ERROR dorkbox.systemTray.SystemTray - Unable to determine the text color in use by your system. Please create an issue and include your full OS configuration and desktop environment, including theme details, such as the theme name, color variant, and custom theme options (if any).

(java:7464): libappindicator-CRITICAL **: app_indicator_set_menu: assertion 'IS_APP_INDICATOR (self)' failed

(java:7464): libappindicator-CRITICAL **: app_indicator_set_menu: assertion 'IS_APP_INDICATOR (self)' failed

(java:7464): libappindicator-CRITICAL **: app_indicator_set_menu: assertion 'IS_APP_INDICATOR (self)' failed

(java:7464): libappindicator-CRITICAL **: app_indicator_set_menu: assertion 'IS_APP_INDICATOR (self)' failed

(java:7464): libappindicator-CRITICAL **: app_indicator_set_menu: assertion 'IS_APP_INDICATOR (self)' failed
```

**Comment by dorkbox** [comment]
Thanks for the report.

It seems that there are also some other issues with your OS, since the theme colors could not be parsed correctly as well. What are the specifics for your OS (ubuntu? x32/x64?) and window manager(Unity? XFCE? Gnome?)

**Comment by apetrelli** [comment]
Kubuntu 17.04, KDE 5.9.5
I had to install libappindicator-3 to make it work, so it is not strictly "native" (should it use Status Notifier? or D-Bus? these are random thoughts though).
With the exception of these warning and this workaround, the systray icon appears correctly and it works.

**Comment by dorkbox** [comment]
Hm. Glad to know it works with `libappindicator-3`, but it should work without as well. I'll run some tests in a VM to see what's going on. It might take a while to get to though, much bigger things going on at work right now.

What does the log say if you don't have `libappindicator-3` installed?

**Comment by apetrelli** [comment]
It's a total mess. It seems that KDE 5 has dropped support for previous way of creating systray icons:
http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/
Uninstalling libappindicator-3 the icon has the infamous grey background and right-clicking does nothing.

Here is the log I see:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dorkbox.util.Swt (file:/home/anpetrel/.m2/repository/com/dorkbox/SystemTray/3.11/SystemTray-3.11.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of dorkbox.util.Swt
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
14:25:22.076 [main] DEBUG dorkbox.systemTray.SystemTray - OS: Linux
14:25:22.083 [main] DEBUG dorkbox.systemTray.SystemTray - Arch: amd64
14:25:22.083 [main] DEBUG dorkbox.systemTray.SystemTray - Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 9
14:25:22.086 [main] DEBUG dorkbox.systemTray.SystemTray - Is Auto sizing tray/menu? true
14:25:22.086 [main] DEBUG dorkbox.systemTray.SystemTray - Is JavaFX detected? false
14:25:22.087 [main] DEBUG dorkbox.systemTray.SystemTray - Is SWT detected? false
14:25:22.266 [main] DEBUG dorkbox.systemTray.SystemTray - Java Swing L&F: Metal
14:25:22.266 [main] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
14:25:22.266 [main] DEBUG dorkbox.systemTray.SystemTray - Force GTK2: false
14:25:22.266 [main] DEBUG dorkbox.systemTray.SystemTray - Prefer GTK3: true
14:25:22.309 [main] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'KDE' desktop environment
14:25:22.426 [main] DEBUG dorkbox.util.jna.linux.GtkLoader - GTK: libgtk-3.so.0
14:25:22.428 [GTK Native Event Loop] DEBUG dorkbox.util.jna.linux.GtkEventDispatch - Running GTK Native Event Loop
14:25:22.541 [main] DEBUG dorkbox.systemTray.SystemTray - GTK Version: 3.22.11
14:25:22.541 [main] DEBUG dorkbox.systemTray.SystemTray - Is the system already running GTK? false
14:25:22.548 [main] DEBUG dorkbox.util.jna.linux.AppIndicator - Error loading library: 'appindicator3'. 
Unable to load library 'appindicator3': Native library (linux-x86-64/libappindicator3.so) not found in resource path (/home/anpetrel/git/scafa/scafa-systray/target/classes:/home/anpetrel/git/scafa/scafa-server/target/classes:/home/anpetrel/.m2/repository/jcifs/jcifs/1.3.17/jcifs-1.3.17.jar:/home/anpetrel/.m2/repository/org/ini4j/ini4j/0.5.4/ini4j-0.5.4.jar:/home/anpetrel/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/anpetrel/.m2/repository/com/dorkbox/SystemTray/3.11/SystemTray-3.11.jar:/home/anpetrel/.m2/repository/org/javassist/javassist/3.22.0-GA/javassist-3.22.0-GA.jar:/home/anpetrel/.m2/repository/net/java/dev/jna/jna/4.3.0/jna-4.3.0.jar:/home/anpetrel/.m2/repository/net/java/dev/jna/jna-platform/4.3.0/jna-platform-4.3.0.jar:/home/anpetrel/.m2/repository/org/slf4j/slf4j-api/1.7.9/slf4j-api-1.7.9.jar:/home/anpetrel/.m2/repository/ch/qos/logback/logback-classic/1.1.6/logback-classic-1.1.6.jar:/home/anpetrel/.m2/repository/ch/qos/logback/logback-core/1.1.6/logback-core-1.1.6.jar)
14:25:22.555 [main] DEBUG dorkbox.util.jna.linux.AppIndicator - Error loading library: 'appindicator'. 
Unable to load library 'appindicator': Native library (linux-x86-64/libappindicator.so) not found in resource path (/home/anpetrel/git/scafa/scafa-systray/target/classes:/home/anpetrel/git/scafa/scafa-server/target/classes:/home/anpetrel/.m2/repository/jcifs/jcifs/1.3.17/jcifs-1.3.17.jar:/home/anpetrel/.m2/repository/org/ini4j/ini4j/0.5.4/ini4j-0.5.4.jar:/home/anpetrel/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/anpetrel/.m2/repository/com/dorkbox/SystemTray/3.11/SystemTray-3.11.jar:/home/anpetrel/.m2/repository/org/javassist/javassist/3.22.0-GA/javassist-3.22.0-GA.jar:/home/anpetrel/.m2/repository/net/java/dev/jna/jna/4.3.0/jna-4.3.0.jar:/home/anpetrel/.m2/repository/net/java/dev/jna/jna-platform/4.3.0/jna-platform-4.3.0.jar:/home/anpetrel/.m2/repository/org/slf4j/slf4j-api/1.7.9/slf4j-api-1.7.9.jar:/home/anpetrel/.m2/repository/ch/qos/logback/logback-classic/1.1.6/logback-classic-1.1.6.jar:/home/anpetrel/.m2/repository/ch/qos/logback/logback-core/1.1.6/logback-core-1.1.6.jar)
14:25:22.562 [main] DEBUG dorkbox.util.jna.linux.AppIndicator - Error loading library: 'appindicator-gtk3'. 
Unable to load library 'appindicator-gtk3': Native library (linux-x86-64/libappindicator-gtk3.so) not found in resource path (/home/anpetrel/git/scafa/scafa-systray/target/classes:/home/anpetrel/git/scafa/scafa-server/target/classes:/home/anpetrel/.m2/repository/jcifs/jcifs/1.3.17/jcifs-1.3.17.jar:/home/anpetrel/.m2/repository/org/ini4j/ini4j/0.5.4/ini4j-0.5.4.jar:/home/anpetrel/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/anpetrel/.m2/repository/com/dorkbox/SystemTray/3.11/SystemTray-3.11.jar:/home/anpetrel/.m2/repository/org/javassist/javassist/3.22.0-GA/javassist-3.22.0-GA.jar:/home/anpetrel/.m2/repository/net/java/dev/jna/jna/4.3.0/jna-4.3.0.jar:/home/anpetrel/.m2/repository/net/java/dev/jna/jna-platform/4.3.0/jna-platform-4.3.0.jar:/home/anpetrel/.m2/repository/org/slf4j/slf4j-api/1.7.9/slf4j-api-1.7.9.jar:/home/anpetrel/.m2/repository/ch/qos/logback/logback-classic/1.1.6/logback-classic-1.1.6.jar:/home/anpetrel/.m2/repository/ch/qos/logback/logback-core/1.1.6/logback-core-1.1.6.jar)
14:25:22.570 [main] DEBUG dorkbox.util.jna.linux.AppIndicator - Error loading library: 'appindicator-gtk'. 
Unable to load library 'appindicator-gtk': Native library (linux-x86-64/libappindicator-gtk.so) not found in resource path (/home/anpetrel/git/scafa/scafa-systray/target/classes:/home/anpetrel/git/scafa/scafa-server/target/classes:/home/anpetrel/.m2/repository/jcifs/jcifs/1.3.17/jcifs-1.3.17.jar:/home/anpetrel/.m2/repository/org/ini4j/ini4j/0.5.4/ini4j-0.5.4.jar:/home/anpetrel/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/anpetrel/.m2/repository/com/dorkbox/SystemTray/3.11/SystemTray-3.11.jar:/home/anpetrel/.m2/repository/org/javassist/javassist/3.22.0-GA/javassist-3.22.0-GA.jar:/home/anpetrel/.m2/repository/net/java/dev/jna/jna/4.3.0/jna-4.3.0.jar:/home/anpetrel/.m2/repository/net/java/dev/jna/jna-platform/4.3.0/jna-platform-4.3.0.jar:/home/anpetrel/.m2/repository/org/slf4j/slf4j-api/1.7.9/slf4j-api-1.7.9.jar:/home/anpetrel/.m2/repository/ch/qos/logback/logback-classic/1.1.6/logback-classic-1.1.6.jar:/home/anpetrel/.m2/repository/ch/qos/logback/logback-core/1.1.6/logback-core-1.1.6.jar)
14:25:22.570 [main] WARN dorkbox.systemTray.SystemTray - Unable to initialize the AppIndicator correctly. Using the Swing Tray type instead.
14:25:22.827 [main] DEBUG dorkbox.systemTray.SystemTray - Tray indicator image size: 22
14:25:22.827 [main] DEBUG dorkbox.systemTray.SystemTray - Tray menu image size: 15
14:25:23.056 [main] ERROR dorkbox.systemTray.SystemTray - Error setting tray icon background color
javassist.CannotCompileException: [source error] getPeer() not found in sun.awt.X11.XTrayIconPeer$XTrayIconEmbeddedFrame
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at dorkbox.systemTray.util.SystemTrayFixes.fixLinux(SystemTrayFixes.java:615)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:892)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1018)
	at com.github.apetrelli.scafa.systray.ScafaSystrayMain.prepareTrayIcon(ScafaSystrayMain.java:42)
	at com.github.apetrelli.scafa.systray.ScafaSystrayMain.main(ScafaSystrayMain.java:36)
Caused by: javassist.compiler.CompileError: getPeer() not found in sun.awt.X11.XTrayIconPeer$XTrayIconEmbeddedFrame
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:749)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atDeclarator(CodeGen.java:743)
	at javassist.compiler.ast.Declarator.accept(Declarator.java:100)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:398)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at javassist.compiler.Javac.compileMethod(Javac.java:169)
	at javassist.compiler.Javac.compile(Javac.java:95)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
	... 6 common frames omitted
14:25:23.205 [main] INFO dorkbox.systemTray.SystemTray - Successfully loaded type: _SwingTray
14:25:23.206 [main] WARN dorkbox.systemTray.SystemTray - Tooltips are not consistent across all platforms and tray types.

**Comment by dorkbox** [comment]
Ok. I'll see what can be done. Might have to do some extra work arounds, but I see whats going on in my debugger.

**Comment by dorkbox** [comment]
This logic surrounding how the menu is set was re-worked in Version 3.17 - and this should no longer happen. Thank you for the bug report.
