### ISSUE TITLE
KDE - The tooltip displays wrong text on KDE

### ISSUE THREAD

**Issue by Nohus** [dorkbox/SystemTray#68]
The tooltip displays wrong text on KDE Plasma 5.8.6:

![bug](https://user-images.githubusercontent.com/11064768/32244570-dccce83c-be70-11e7-81ff-165ca72d4381.png)

It displays "SystemTray" instead of the text I'm setting. I know that the tooltip is not supported everywhere, but since it displays the library's name, the text must be coming from the library and as such  it should be possible to change it.

**Comment by dorkbox** [comment]
Thanks! Can you set `SystemTray.DEBUG=true;` and include an output of the log so I can know a little more about the behavior of the library on your system?

**Comment by Nohus** [comment]
Done, output is at my comment at issue #67

**Comment by larsrh** [comment]
I can confirm this issue on Arch and KDE.

**Comment by dorkbox** [comment]
The tooltip being wrong is a symptom of how a javascript extension is labeled. It not really something that can be changed dynamically without having to reload the entire UI ... At least, I don't know how to do that yet.

I'll look into seeing if there are other ways to solve this, but I don't know if it's possible at all.

**Comment by Nohus** [comment]
You mention reloading the entire UI to change the text, in my case I just want it to display static text that never changes (the name of my app). Would this be possible? My tooltip text is known at compile time. I could fix it for my app by forking this library and doing a find and replace for "SystemTray", but this is obviously not the proper solution.

If this can't be fixed, can you tell me where does the tooltip text "SystemTray" come from? Then I could replace just this one piece of code with my name.

**Comment by dorkbox** [comment]
Sorry for getting back so late (the holidays completely wrecked all my free time) - yes, this is possible and I will add a "static" tooltip option that cannot be changed.

**Comment by dorkbox** [comment]
The change to enable this has been committed (e0e103be083eb1d16a72fa7a0ca58b6307fa6cce), and is configured via `SystemTray.APP_NAME`. This will be part of the next release

**Comment by Nohus** [comment]
Is a release with the fix planned? 3 years later I would still greatly appreciate getting the fix.

**Comment by dorkbox** [comment]
Just a heads up, I've started working on this project again.

**Comment by Nohus** [comment]
@dorkbox `SystemTray.APP_NAME` is still not present in the 4.4 release. Any update on this?

**Comment by Nohus** [comment]
In the meantime I've added it to my fork: https://github.com/Nohus/SystemTray
