### ISSUE TITLE
Ubuntu 17.10 Support

### ISSUE THREAD

**Issue by tresf** [dorkbox/SystemTray#71]
Just tried running SystemTray 3.11 on Ubuntu 17.10 x64 using openjdk-8:

```
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
[ERROR] 2017-11-28 13:47:29,324 @ dorkbox.systemTray.SystemTray:775
	SystemTray initialization failed. (Unable to discover which implementation to use). Falling back to the Swing Tray.
[ERROR] 2017-11-28 13:47:30,564 @ dorkbox.systemTray.SystemTray:936
	Unable to create tray type: '_SwingTray'
```

**Comment by tresf** [comment]
Fixed typo, 17.10, not 17.04.

**Comment by tresf** [comment]
Ok, the ubuntu fix does fix the `invalid string constant "murrine-scrollbar"` error, but SystemTray 3.11 still fails to load.

**Comment by dorkbox** [comment]
It seems that Gnome 3.26 has changed everything... Nothing I currently have works on it, and it looks list I will have to add a native DBus implementation to support it.

**Comment by DiWizard** [comment]
Ubuntu 17.10 + "TopIcons Plus" extension [ https://extensions.gnome.org/extension/1031/topicons/ ]
SystemTray demo project works well.

**Comment by dorkbox** [comment]
Interesting... And great find. This will make 17.10 compatibility a lot easier.

Thanks!!

**Comment by tresf** [comment]
> Interesting... And great find. This will make 17.10 compatibility a lot easier.

Since ISVs don't have control over the desktops they deploy to, I'd disagree with this statement.  No 3rd party software need to be installed on Mac or Linux for a System Tray to work properly.  Using legacy packages is only a stop-gap in my opinion.  I hope you feel the same way. <3

**Comment by tresf** [comment]
**Correction:

No 3rd party software need to be installed on Mac or **Windows**

**Comment by dorkbox** [comment]
>Since ISVs don't have control over the desktops they deploy to, ...  Using legacy packages is only a stop-gap in my opinion. I hope you feel the same way. <3

I do and I'm really, really hoping a native DBUS implementation solves this problem, because I hate the idea of having an extension to do it...

*Some background...*

So for some versions of Gnome, Gnome leadership decided to *hide* all icons by default, and only show them if you press magic key combinations or click on a *not-obvious-at-all button* at the bottom left of the screen. 

Because I couldn't figure out how to get around this restriction showing tray icons using C/C++ (the process is to start with C/C++ and then port the code to Java) I had to resort to using an extension, which the SystemTray runtime will automatically install. Nothing 3rd party, since I maintain the extension and it is only available via the SystemTray (however, it's an extension and I hate having to use it).

The extension installed is very similar to TopIcons, and it was previously excluded from Ubuntu, just because the Ubuntu Gnome implementations were completely different than "official" gnome, even though both report themselves as using gnome.

As a stop-gap solution that will work until (hopefully) a DBUS implementation fixes it, these extensions are sadly the only way I know how to show an icon in the tray area.

**Comment by tresf** [comment]
@dorkbox what if we leveraged something like Steam does instead... Can Java do this?

<img width="324" alt="screen shot 2018-03-31 at 10 33 48 pm" src="https://user-images.githubusercontent.com/6345473/38169266-a0f8e29a-3533-11e8-8655-50cefdc865d9.png">

**Comment by tresf** [comment]
So the `Actions` appear to be part of the `.desktop` shortcut specification. 

```ini
[Desktop Entry]
Name=Steam
Comment=Application for managing and playing games on Steam
Exec=/usr/bin/steam %U
Icon=steam
Terminal=false
Type=Application
Categories=Network;FileTransfer;Game;
MimeType=x-scheme-handler/steam;
Actions=Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;
```

And then the executable path and language translations are as follows:
```ini
[Desktop Action Store]
Name=Store
Name[de]=Shop
Name[es]=Tienda
Name[fr]=Magasin
Name[it]=Negozio
Name[pt]=Loja
Name[ru]=Магазин
Name[zh_CN]=商店
Name[zh_TW]=商店
Exec=steam steam://store
```

I wanted to offer this information because it was hard to find on the internet and I wanted to clarify that it does not appear to be a solution we can leverage after the application has been started.

**Comment by dorkbox** [comment]
It's now working in Ubuntu 17.10. 

note: there are some harmless GLIB warnings now, that I can't seem to get rid of. The test examples work as expected.  I will do a release shortly.

**Comment by dorkbox** [comment]
Version 3.17 is now released, there is support now for Ubuntu 17.10, 18.04, Fedora 27, 28, 29, and Debian 9.5 (+ all DE's possible from it's installer, so Gnome3, KDE, Xfce, LXDE, and MATE). ElementaryOS 5.0 *removed* support for tray icons entirely, however a workaround is possible to get them back via some compiled libraries.

**Comment by tresf** [comment]
@dorkbox FYI, I've [found a reasonable way](https://github.com/qzind/tray/pull/411) to draw the menu at the task bar using a minimize/restore listener on a 1px x 1px window, wanted to share.
![ezgif-2-f6c1a3068cac](https://user-images.githubusercontent.com/6345473/52255064-f16fd680-28de-11e9-8e86-917fae4be720.gif)

**Comment by dorkbox** [comment]
That is fantastic!

Something you might find useful, is that I have re-written the macos tray to natively support icons in the menu. (See: https://git.dorkbox.com/dorkbox/SystemTray for screenshots). There is still the fallback of AWT, but having icons there as well is a nice improvement. I've also re-written the windows one (to fix scaling bugs) to use JNA as well, but there are some interesting menu position bugs w.r.t. monitor scaling. HiDPI is tricky stuff when the JVM doesn't fully support it. Even IntelliJ struggles with HiDPI scaling bugs on windows, and every three updates seems to be a JVM scaling bug fix.

**Comment by tresf** [comment]
Some notable findings:

- Prevent double icon by using `.desktop` entry `StartupWMClass=<App-Name>`
- Prevent hanging menu on Fedora by adding focus listener to hidden `JFrame`
- Fix unclickabe menu by calling `show(...)` first, then `setLocation(...)` to mouse position immediately.
- Fix menu position by detecting screen boundaries (behave like `show(...)`, despite using setLocation
- ... as always I've chosen to mimic the AWT class to lessen the code changes from base Java `SystemTray`.

**Comment by dorkbox** [comment]
> The state of libappindicator (or lack thereof) has forced us to write our own workaround.

Yes, the inconsistent state of libappindicator is quite frustrating, and your work looks like a great workaround.

> As always, feel free to use what you'd like out of out tray source for this project.

Thank you! Do I still have permission to use it under the Apache 2 license?

**Comment by tresf** [comment]
> Thank you! Do I still have permission to use it under the Apache 2 license?

Absolutely.  Anything inside the [`src\qz\ui\tray`](https://github.com/qzind/tray/tree/2.0/src/qz/ui/tray) folder can be relicensed Apache 2.
