### ISSUE TITLE
Bug in OracleJVM detection in SystemTrayFixes

### ISSUE THREAD

**Issue by mprunet** [dorkbox/SystemTray#75]
On Oracle JVM fixes are not applied, because the condition is inverted in class : SystemTrayFixes

> 
    private static boolean isOracleVM() {
        String vendor = System.getProperty("java.vendor").toLowerCase(Locale.US);
        return !vendor.contains("sun ") && !vendor.contains("oracle ");
    }

It should be : 
> 
    private static boolean isOracleVM() {
        String vendor = System.getProperty("java.vendor").toLowerCase(Locale.US);
        return vendor.contains("sun ") || vendor.contains("oracle "); 
    }

**Comment by dorkbox** [comment]
Fixed. Thanks for reporting!
