### ISSUE TITLE
OnClick handler for indicator

### ISSUE THREAD

**Issue by Djaler** [dorkbox/SystemTray#78]
In some DE I can call tray action by left-clicking on indicator. For example, it cause window open. Can I make something like this with SystemTray?

**Comment by dorkbox** [comment]
Having something "cross platform" that behaves in radically different ways depending on what Linux DE is used is a really bad idea. I've changed my mind in the past on some things -- but there is so much work that needs to be done to get SystemTray working with the latest release of Gnome right now it's insane.

If it is possible to get a (very, very simple) tray icon left/right click events in the list of Linux OS's that I support using https://github.com/hypfvieh/dbus-java (which is a dbus implementation I am considering using), then I will absolutely include separate left/right click actions -- I plan on migrating much of the current back-end implementation to a dbus system.
