### ISSUE TITLE
Menu items listeners not working on Linux

### ISSUE THREAD

**Issue by kuc** [dorkbox/SystemTray#8]
Menu shows up and open correctly, but clicking menu items with any button does nothing :(

Same code works flawlessly on Windows.

---------------------

BTW: I can't find version `1.11` form README on any maven repository.

**Comment by dorkbox** [comment]
It seems there was a problem uploading the artifacts for `v1.11` -- thanks for bringing this to my attention.

I just re-uploaded a build (`v1.12`) and verified the download link works. It does take a while for the primary maven repo to pick it up.

**Comment by kuc** [comment]
So this bug is fixed in unreleased `1.11` version?

**Comment by dorkbox** [comment]
Forgot about that -- it's working in various versions Linux -- what OS specifically are there issues?

**Comment by kuc** [comment]
Fresh install of Ubuntu 15.10 in virtualbox. Java 8u72.

**Comment by dorkbox** [comment]
Oh that's really odd. I know it works (or used to work) in 14.04 - so I'll see what's happened.

**Comment by kuc** [comment]
Updating all system packages and installing `libappindicator1` not helped.

**Comment by dorkbox** [comment]
hm, good to know. The appindicator stuff is voodoo, mostly since NO ONE uses the same version -- and the different versions are, well, different.

**Comment by dorkbox** [comment]
The menu shows up, and the icons are correct?

**Comment by kuc** [comment]
Yup, that works correctly. Only event listeners are not called.

**Comment by dorkbox** [comment]
Hm - ok, I spun up the vbox VM with ubuntu 15.10 (no updates installed) and ran the test application - and everything works (minus menu icons, but that's because it's running libappindicator3).

Can you clone the repo (you'll need slf4j, the utilities lib, and JNA) and run the "TestTray" from source? Something is going on if the menu callbacks aren't working, and I can't reproduce it.

**Comment by kuc** [comment]
You are talking about [this file](https://github.com/dorkbox/SystemTray/blob/master/test/dorkbox/TestTray.java)?

I had a problem running this class _as-is_. Could I setup repo with mini-maven test project instead?
Maybe this problem only manifest with using this project as maven library...

**Comment by dorkbox** [comment]
Yea, that file. It will probably work if you run that from a test project.

It wouldn't surprise me if it was a maven problem...

**Comment by kuc** [comment]
>It will probably work if you run that from a test project.

And what with `libs/jna/linux_64/libjna.so` file in that case? It's missing, there is no subdirectory `libs` here.


>It wouldn't surprise me if it was a maven problem...

Not a "maven problem", but more a problem that maybe packaged JARs are missing something. But no errors are logged.

**Comment by dorkbox** [comment]
you'll need JNA (maven should pull it down), and then load it. I'll clarify how to use JNA

**Comment by kuc** [comment]
>you'll need JNA (maven should pull it down), and then load it.

I know, and it's happening when I add SystemTray as maven dependency, but setting up files and directories for TestTray.java isn't very well documented.

**Comment by dorkbox** [comment]
hm. what would make it easier? It should be you just need that file + the image, and that's it.

**Comment by kuc** [comment]
>hm. what would make it easier?

If after cloning the repo I can run it in one step with `insert command here` :)

But don't worry, I'll make that test repo and we'll could see if problem can be reproduced.

**Comment by dorkbox** [comment]
ahh, i see.

I usually run this from within my IDE. :)

**Comment by kuc** [comment]
Eclipse? That will explain that strange `libs/` catalog and that the lines like `TestTray.class.getResource("mail.000000.24.png").toExternalForm().substring(5);` are working for you :wink:

**Comment by dorkbox** [comment]
IntelliJ actually :)

I'm working on having it accept URL/InputStream, which will solve that problem

**Comment by kuc** [comment]
>IntelliJ actually

So just like me :smile: 

>I'm working on having it accept URL/InputStream, which will solve that problem

Just what I sayd, just `InputStream` would be enough :wink:

**Comment by kuc** [comment]
Really strange - I created simple test project that only display tray menu, and it's now working properly on Ubuntu, too :confused: 

Do you think it's may have something with from what thread the system tray is initialized?
In other project I use JavaFX and have previously said problems on Ubuntu.

**Comment by dorkbox** [comment]
hm. Interesting -- this runs outside of JavaFX - it actually does it's thing via GTK.

It could be an issue with the thread it's run on -- I would suggest not having it created on the javaFX thread.

**Comment by dorkbox** [comment]
continuing the though --- this shouldn't matter *WHAT* thread it's started on, so if you're willing figure out what's going on, I'll try to make whatever changes in the back-end to make it work.

**Comment by kuc** [comment]
**GOOD NEWS**, I isolated the problem :smiley:  Yeah, thread doesn't matter.

The problem was that I wasn't assigning newly created `SystemTray` instance to class field, only to local variable - so it get quickly GC'd by JVM. While this doesn't matter for Swing/AWT-based tray menu, GTK-based menu stops working.

Test app worked, because objects created in `main()` method are never GC'd.

Maybe you could refactor `SystemTray` to always returning singleton, and we could adding and removing tray icons to/from it? I'm talking about API similar to AWT system tray.

----------------

BTW I noticed that you are detecting SWT by doing
```
Class<?> swtClass = Class.forName("org.eclipse.swt.widgets.Display");
    if (swtClass != null) {
       hasSWT_ = true;
}
```

But this will cause problems if I have SWT on classpath, but not using it. This is a real use case because I plan using SWT only on Windows, while always packaging it to application JAR.

**Comment by dorkbox** [comment]
Hm, the singleton idea makes a lot of sense, i'll add that. Not sure what to do about SWT though, since it already starts a GTK thread (if it's in use) which will break what I have as only 1 GTK thread allowed, AFAIK.

**Comment by dorkbox** [comment]
good news about SWT, i can remove that logic, since the thread initialization is ignored if it's already started (version >= 2.24) https://developer.gnome.org/glib/stable/glib-Deprecated-Thread-APIs.html#g-thread-init

**Comment by kuc** [comment]
:cool: 

Because that two things belong to separate issues, I'm closing this one.
