### ISSUE TITLE
Allow notifications through system tray

### ISSUE THREAD

**Issue by bobcat4848** [dorkbox/SystemTray#87]
Normally, through the native java SystemTray, you are able to send a notification/message and I was wondering if you could replicate something similar to this in your library.

Thanks.

**Comment by dorkbox** [comment]
This is not currently available in a cross-platform way (the "balloon notification" is windows only), and so there is another project that does this, since notifications are beyond the scope of a tray icon/menu. 

Please see https://github.com/dorkbox/Notify
