### ISSUE TITLE
Scaling doesn't work correctly on Windows 10 with 4k display

### ISSUE THREAD

**Issue by moromindful** [dorkbox/SystemTray#92]
Hello, my setup is the following:
OS: Windows 10 Home
Resolution: 3840 x 2160
Scale: 250%

Debug Info:
05:39:39.569 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - OS: Windows 10
05:39:39.573 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Arch: amd64
05:39:39.573 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_181
05:39:39.573 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is Auto sizing tray/menu? true
05:39:39.577 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is JavaFX detected? true
05:39:39.578 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is SWT detected? false
05:39:39.634 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Java Swing L&F: Metal
05:39:39.634 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
05:39:39.832 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Tray indicator image size: 40
05:39:39.832 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Tray menu image size: 16
05:39:39.939 [JavaFX Application Thread] INFO dorkbox.systemTray.SystemTray - Successfully loaded type: _WindowsNativeTray
05:39:39.940 [JavaFX Application Thread] WARN dorkbox.systemTray.SystemTray - Tooltips are not consistent across all platforms and tray types.

This is what I get: [https://paste.pics/c0af0ca829510a3d21cf52047f2dee57](url)

And if I use tray type swing:
05:44:38.556 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Forced tray type: Swing
05:44:38.763 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Tray indicator image size: 40
05:44:38.763 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Tray menu image size: 40
05:44:38.841 [JavaFX Application Thread] INFO dorkbox.systemTray.SystemTray - Successfully loaded type: _SwingTray

This is what I get: [https://paste.pics/4786751385b17f1c8069165a8c973efe](url)

Also I have ENABLE_SHUTDOWN_HOOK = true, but the icon is still in the system tray even after the jvm shutdown and I need to hover over it to make it disappear.

**Comment by dorkbox** [comment]
I'm not sure if I can correctly fix the menu text, but I can fix the image size.

**Comment by dorkbox** [comment]
Image size has been fixed in version 3.17.
