### ISSUE TITLE
icon looks horrible on windows 10

### ISSUE THREAD

**Issue by camhart** [dorkbox/SystemTray#93]
With AUTO_SIZE set to true, the icon looks horrible on windows 10.  However even when I set it to false, and pass in an image that's 32x32 (or 24x24) they all look crappy (although way better than with AUTO_SIZE set to true).

Any ideas?

**Comment by dorkbox** [comment]
You're using an out-of-date version, can you try the latest?

Also, the project has moved (hence the note in the readme).

> The project development, source code, and issues have moved to https://git.dorkbox.com/dorkbox/SystemTray

**Comment by dorkbox** [comment]
Which JVM are you using? You can also get a diagnostic report via `SystemTray.DEBUG=true;`

**Comment by dorkbox** [comment]
I've now added screenshots to the readme. With the latest version, I don't see any issues regarding the size of the tray/menu icons. If you are still having issues, can you include screenshots and attach the images to the git issue to help me track down what is going on?
