### ISSUE TITLE
Tray in elementary OS Juno

### ISSUE THREAD

**Issue by Djaler** [dorkbox/SystemTray#96]
There are no ayatana tray support in latest elementary OS release (5.0). So, SystemTray should not work on it

**Comment by dorkbox** [comment]
There are work-arounds. Please see the official documentation: https://git.dorkbox.com/dorkbox/SystemTray, and the workaround itself here: https://git.dorkbox.com/dorkbox/elementary-indicators

**Comment by Djaler** [comment]
I know that I can get tray back. But what if I don't? Application should know, is there are tray or not. For example, if tray is exists, application can minimize to tray instead of closing. But now, if I minimize such application in Juno, I can't open it again because there are no tray (but app think it is)

**Comment by dorkbox** [comment]
That makes sense. Can you open an issue in the right spot for this, and I'll add it to the next release.

**Comment by Djaler** [comment]
> in the right spot for this
What do you mean?

**Comment by dorkbox** [comment]
I don't use github anymore. Go here: https://git.dorkbox.com/dorkbox/SystemTray

**Comment by Djaler** [comment]
Hmm, ok. But can I ask, why?

**Comment by dorkbox** [comment]
I don't want to get into too much politics, but i don't use services owned or operated by microsoft.

**Comment by Djaler** [comment]
Why not gitlab and bitbucket? I mean, something where users can already have accounts

**Comment by dorkbox** [comment]
i don't have an account on those sites.

**Comment by Djaler** [comment]
Also, what about this? :)
![image](https://user-images.githubusercontent.com/7964583/49152909-3a2a7280-f325-11e8-9c79-556a1a1977c0.png)
![image](https://user-images.githubusercontent.com/7964583/49152921-44e50780-f325-11e8-9757-acdad98113ad.png)

**Comment by dorkbox** [comment]
That means they paid me money. That doesn't mean I use their stuff.
